# USPA Judge Test Questions - All Chapters
# Each chapter has Regional (25 questions) and National (25 questions) tests

TESTS = {
    "ch8_regional": {
        "name": "Chapter 8: Accuracy Landing - Regional Test",
        "chapter": "8",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "What is the diameter of the dead-center target on the AMD?", "options": ["1 cm", "2 cm", "3 cm", "5 cm"], "correct": 1, "correct_section": "8.1.3.1.1"},
            {"id": 2, "question": "What is the exit altitude for Individual Accuracy Landing?", "options": ["2,500 feet", "3,000 feet", "3,500 feet", "4,000 feet"], "correct": 1, "correct_section": "8.1.5.3"},
            {"id": 3, "question": "What is the exit altitude for Team Accuracy?", "options": ["3,000 feet", "3,500 feet", "4,000 feet", "4,500 feet"], "correct": 1, "correct_section": "8.1.5.4.1"},
            {"id": 4, "question": "What is the maximum scheduled number of rounds for Individual Accuracy Landing?", "options": ["Six", "Eight", "Ten", "Twelve"], "correct": 2, "correct_section": "8.1.6.1"},
            {"id": 5, "question": "What is the maximum scheduled number of rounds for Team Accuracy?", "options": ["Six", "Eight", "Ten", "Twelve"], "correct": 1, "correct_section": "8.1.6.2"},
            {"id": 6, "question": "At what wind speed must wind be monitored constantly and documented every 2 minutes?", "options": ["2 m/s", "3 m/s", "5 m/s", "6 m/s"], "correct": 1, "correct_section": "8.1.7.2"},
            {"id": 7, "question": "What is the range for maximum allowable wind speed set by officials?", "options": ["4-6 m/s", "5-7 m/s", "6-7.5 m/s", "7-9 m/s"], "correct": 2, "correct_section": "8.1.7.3"},
            {"id": 8, "question": "A landing off the AMD is scored as what distance?", "options": ["10 cm", "15 cm", "16 cm", "20 cm"], "correct": 2, "correct_section": "8.1.8.1.2"},
            {"id": 9, "question": "If a competitor lands on unreset AMD due to insufficient team separation, what score is given?", "options": ["10 cm", "15 cm", "16 cm", "Rejump"], "correct": 1, "correct_section": "8.1.8.2.3"},
            {"id": 10, "question": "How many principal judges are required at the target for Accuracy Landing?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "8.1.9.1"},
            {"id": 11, "question": "What is the radius of the marked circle the AMD must be centered within?", "options": ["10 meters", "15 meters", "20 meters", "25 meters"], "correct": 2, "correct_section": "8.1.10.3"},
            {"id": 12, "question": "What is the minimum thickness of the foam tuffet?", "options": ["20 cm", "25 cm", "30 cm", "35 cm"], "correct": 2, "correct_section": "8.1.10.3.2"},
            {"id": 13, "question": "What is the approximate diameter of the tuffet?", "options": ["3 meters", "4 meters", "5 meters", "6 meters"], "correct": 2, "correct_section": "8.1.10.3.2"},
            {"id": 14, "question": "What is the maximum aircraft speed at time of exit?", "options": ["80 knots", "87 knots", "95 knots", "100 knots"], "correct": 1, "correct_section": "8.1.12.2"},
            {"id": 15, "question": "What happens if the event is interrupted for 60 minutes or more?", "options": ["Competition cancelled", "WDI dropped", "Rejumps for all", "New draw required"], "correct": 1, "correct_section": "8.1.4.1"},
            {"id": 16, "question": "From what altitude is the Wind Drift Indicator dropped?", "options": ["2,000 feet", "2,500 feet", "3,000 feet", "3,500 feet"], "correct": 1, "correct_section": "8.1.4.1"},
            {"id": 17, "question": "The large wind indicator must respond to winds of at least what speed?", "options": ["1 m/s", "2 m/s", "3 m/s", "4 m/s"], "correct": 1, "correct_section": "8.1.10.1.1"},
            {"id": 18, "question": "How far from the target center is the large wind indicator positioned?", "options": ["30 meters", "40 meters", "50 meters", "60 meters"], "correct": 2, "correct_section": "8.1.10.1.1"},
            {"id": 19, "question": "What is the minimum horizontal diameter of footwear touching the target?", "options": ["0.5 cm", "1 cm", "1.5 cm", "2 cm"], "correct": 1, "correct_section": "8.1.11.2.1"},
            {"id": 20, "question": "At what ground wind speed is the event automatically interrupted?", "options": ["7 m/s", "8 m/s", "9 m/s", "10 m/s"], "correct": 2, "correct_section": "8.1.7.3.4"},
            {"id": 21, "question": "How long must scoring stop when wind exceeds the limit?", "options": ["15 seconds", "30 seconds", "45 seconds", "60 seconds"], "correct": 1, "correct_section": "8.1.7.3.2"},
            {"id": 22, "question": "Teams landing with fewer than four members receive what score for each missing member?", "options": ["10 cm", "15 cm", "16 cm", "20 cm"], "correct": 2, "correct_section": "8.1.8.2.6"},
            {"id": 23, "question": "What is the minimum number of rounds to constitute a meet for Individual Accuracy?", "options": ["One", "Two", "Three", "Four"], "correct": 0, "correct_section": "8.1.6.1"},
            {"id": 24, "question": "Within how many meters of the target is the wind direction streamer placed?", "options": ["10 meters", "15 meters", "20 meters", "25 meters"], "correct": 2, "correct_section": "8.1.10.1.2"},
            {"id": 25, "question": "What is the minimum height above ground for the wind-speed measuring device?", "options": ["4 meters", "5 meters", "6 meters", "8 meters"], "correct": 2, "correct_section": "8.1.10.2.2"},
        ]
    },
    "ch8_national": {
        "name": "Chapter 8: Accuracy Landing - National Test",
        "chapter": "8",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "How much may the Meet Director lower Individual Accuracy exit altitude to negotiate weather?", "options": ["200 feet", "300 feet", "400 feet", "500 feet"], "correct": 1, "correct_section": "8.1.5.3"},
            {"id": 2, "question": "What is the lowest altitude Team Accuracy may be lowered to for weather?", "options": ["2,500 feet", "2,800 feet", "3,000 feet", "3,200 feet"], "correct": 1, "correct_section": "8.1.5.4.1"},
            {"id": 3, "question": "For how long is the target covered when ground wind exceeds 9 m/s?", "options": ["3 minutes", "5 minutes", "7 minutes", "10 minutes"], "correct": 1, "correct_section": "8.1.7.3.4"},
            {"id": 4, "question": "What is the maximum change in wind direction that triggers the limit when wind exceeds 3 m/s?", "options": ["45 degrees", "60 degrees", "90 degrees", "120 degrees"], "correct": 2, "correct_section": "8.1.7.5"},
            {"id": 5, "question": "A competitor landing within how many seconds after wind change is offered a rejump?", "options": ["15 seconds", "30 seconds", "45 seconds", "60 seconds"], "correct": 1, "correct_section": "8.1.7.5.1"},
            {"id": 6, "question": "During final approach, only principal judges are allowed within how many meters?", "options": ["3 meters", "5 meters", "7 meters", "10 meters"], "correct": 1, "correct_section": "8.1.9.4.1"},
            {"id": 7, "question": "The angle of footwear sole touching the target must be within what tolerance of 90 degrees?", "options": ["10 degrees", "15 degrees", "20 degrees", "25 degrees"], "correct": 1, "correct_section": "8.1.11.2.1"},
            {"id": 8, "question": "Who determines an erroneous AMD reading?", "options": ["Chief Judge alone", "Event Judge alone", "Simple majority of principal judges", "Unanimous judges"], "correct": 2, "correct_section": "8.1.13.1.1"},
            {"id": 9, "question": "A competitor with main canopy malfunction must signal by what method?", "options": ["Waving arms", "Arms and legs apart", "Spinning", "Pulling reserve immediately"], "correct": 1, "correct_section": "8.1.13.1.2"},
            {"id": 10, "question": "In Team Accuracy rounds 1-8, what is the jumping order?", "options": ["Teams then individuals", "Individuals then teams", "Alternating", "Random draw"], "correct": 1, "correct_section": "8.1.5.1"},
            {"id": 11, "question": "Rounds nine and ten of Accuracy are in what order?", "options": ["Team only", "Individual, reverse order of standing", "Individual, random order", "Team, reverse order"], "correct": 1, "correct_section": "8.1.5.2"},
            {"id": 12, "question": "How many jumpers may exit per pass in Individual Accuracy?", "options": ["One only", "One or two", "Up to three", "Up to four"], "correct": 1, "correct_section": "8.1.5.3"},
            {"id": 13, "question": "Who is responsible for selecting the proper exit point?", "options": ["Pilot", "Chief Judge", "Competitor/team", "Meet Director"], "correct": 2, "correct_section": "8.1.5.5"},
            {"id": 14, "question": "What happens to competitors waved off during halted jumping?", "options": ["Score counts", "16 cm score", "Must rejump", "Disqualified"], "correct": 2, "correct_section": "8.1.7.3.4"},
            {"id": 15, "question": "The AMD must be capable of measuring to what minimum distance?", "options": ["10 cm", "15 cm", "16 cm", "20 cm"], "correct": 2, "correct_section": "8.1.10.3.1"},
            {"id": 16, "question": "A competitor landing 15 seconds before wind exceeds limit and not scoring dead center is offered what?", "options": ["Score stands", "Rejump", "16 cm score", "Disqualification"], "correct": 1, "correct_section": "8.1.7.3.3"},
            {"id": 17, "question": "What must happen before the event continues after interruption due to winds aloft?", "options": ["5-minute wait", "New briefing", "New WDI dropped", "Equipment check"], "correct": 2, "correct_section": "8.1.9.9.3"},
            {"id": 18, "question": "Substitutes to team composition are permitted after competition begins.", "options": ["True", "False", "Only with CJ approval", "Only for injury"], "correct": 1, "correct_section": "8.1.3.2.2"},
            {"id": 19, "question": "What device must be used to alert judges of a wind hold?", "options": ["Radio", "Flag", "Audible device", "Light signal"], "correct": 2, "correct_section": "8.1.7.4"},
            {"id": 20, "question": "If canopy condition resulted from faulty equipment or improper judgment, what happens?", "options": ["Rejump awarded", "No rejump awarded", "Half score", "Disqualification"], "correct": 1, "correct_section": "8.1.13.1.2"},
            {"id": 21, "question": "For canopy conflict with own teammate, the team receives what?", "options": ["Rejump", "No rejump, score counts", "16 cm for affected", "Disqualification"], "correct": 1, "correct_section": "8.1.13.2.2"},
            {"id": 22, "question": "If AMD is defective or not reset and first contact was on it, what is offered?", "options": ["Score stands", "Rejump", "16 cm", "Dead center"], "correct": 1, "correct_section": "8.1.13.3"},
            {"id": 23, "question": "In case of tie in top three places, how many tie-break rounds maximum?", "options": ["One", "Two", "Three", "Unlimited"], "correct": 1, "correct_section": "8.2.2.3"},
            {"id": 24, "question": "Winds aloft refers to winds occurring above what?", "options": ["500 feet", "1000 feet", "Wind-speed device altitude", "Exit altitude"], "correct": 2, "correct_section": "8.A.1.2.8"},
            {"id": 25, "question": "The control pad when struck at any point scores what?", "options": ["10 cm", "15 cm", "16 cm", "Maximum"], "correct": 2, "correct_section": "8.A.1.2.3"},
        ]
    },
    "ch9_regional": {
        "name": "Chapter 9: Formation Skydiving - Regional Test",
        "chapter": "9",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "What is the exit altitude for 4-Way Formation Skydiving?", "options": ["9,500 feet", "10,500 feet", "11,500 feet", "13,000 feet"], "correct": 1, "correct_section": "9.5.2.1"},
            {"id": 2, "question": "What is the working time for 4-Way FS?", "options": ["30 seconds", "35 seconds", "40 seconds", "50 seconds"], "correct": 1, "correct_section": "9.5.2.3"},
            {"id": 3, "question": "What is the exit altitude for 8-Way FS?", "options": ["10,500 feet", "11,000 feet", "12,000 feet", "13,000 feet"], "correct": 3, "correct_section": "9.5.3.1"},
            {"id": 4, "question": "What is the working time for 8-Way FS?", "options": ["35 seconds", "40 seconds", "45 seconds", "50 seconds"], "correct": 3, "correct_section": "9.5.3.3"},
            {"id": 5, "question": "How many points are deducted for each omission?", "options": ["One", "Two", "Three", "Four"], "correct": 2, "correct_section": "9.7.1.2"},
            {"id": 6, "question": "What is the minimum score for any round?", "options": ["Negative three", "Negative one", "Zero", "One"], "correct": 2, "correct_section": "9.7.1.4"},
            {"id": 7, "question": "What is the maximum scheduled number of rounds for 4-Way and 8-Way FS?", "options": ["Six", "Eight", "Ten", "Twelve"], "correct": 2, "correct_section": "9.4.3.3"},
            {"id": 8, "question": "What is the exit altitude for 2-Way MFS and 4-Way VFS?", "options": ["10,500 feet", "11,000 feet", "12,000 feet", "13,000 feet"], "correct": 3, "correct_section": "9.5.1.1"},
            {"id": 9, "question": "What is the working time for 2-Way MFS and 4-Way VFS?", "options": ["30 seconds", "35 seconds", "40 seconds", "50 seconds"], "correct": 1, "correct_section": "9.5.1.3"},
            {"id": 10, "question": "How many members minimum must remain on a 4-Way team to continue competition?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "9.3.2.1"},
            {"id": 11, "question": "How many members minimum must remain on an 8-Way team?", "options": ["Six", "Seven", "Eight", "Nine"], "correct": 1, "correct_section": "9.3.3.1"},
            {"id": 12, "question": "What is the exit altitude for 16-Way FS?", "options": ["11,000 feet", "12,000 feet", "13,000 feet", "14,000 feet"], "correct": 2, "correct_section": "9.5.5.1"},
            {"id": 13, "question": "What is the working time for 16-Way FS?", "options": ["35 seconds", "40 seconds", "45 seconds", "50 seconds"], "correct": 3, "correct_section": "9.5.5.3"},
            {"id": 14, "question": "What is the exit altitude for 10-Way FS?", "options": ["10,000 feet", "11,000 feet", "12,000 feet", "13,000 feet"], "correct": 1, "correct_section": "9.5.4.1"},
            {"id": 15, "question": "What is the total working time for 10-Way FS?", "options": ["35 seconds", "40 seconds", "45 seconds", "50 seconds"], "correct": 1, "correct_section": "9.5.4.4"},
            {"id": 16, "question": "10-Way formations must be held for a minimum of how many seconds?", "options": ["Three", "Four", "Five", "Six"], "correct": 2, "correct_section": "9.5.4.3"},
            {"id": 17, "question": "How much advance notice of draw results must teams receive before competition starts?", "options": ["One hour", "Two hours", "Three hours", "Four hours"], "correct": 1, "correct_section": "9.4.1.2"},
            {"id": 18, "question": "What penalty percentage is deducted if judges cannot determine start of working time?", "options": ["10%", "15%", "20%", "25%"], "correct": 2, "correct_section": "9.5.2.2.2"},
            {"id": 19, "question": "How many members maximum can a 4-Way team have including videographer?", "options": ["Four", "Five", "Six", "Seven"], "correct": 2, "correct_section": "9.3.2.1"},
            {"id": 20, "question": "How many members maximum can an 8-Way team have including videographer?", "options": ["Nine", "Ten", "Eleven", "Twelve"], "correct": 2, "correct_section": "9.3.3.1"},
            {"id": 21, "question": "What is the maximum scheduled number of rounds for 16-Way and 10-Way?", "options": ["Four", "Six", "Eight", "Ten"], "correct": 1, "correct_section": "9.4.3.4"},
            {"id": 22, "question": "4-Way exit altitude may be lowered to what for weather without working time change?", "options": ["8,500 feet", "9,000 feet", "9,500 feet", "10,000 feet"], "correct": 2, "correct_section": "9.5.2.1"},
            {"id": 23, "question": "A grip consists of contact between what and another jumper?", "options": ["Any body part", "Palm side of hand/fingers", "Fist", "Wrist"], "correct": 1, "correct_section": "9.8.2"},
            {"id": 24, "question": "For 10-Way, where must the videographer record an image before team exit?", "options": ["Target", "Aircraft door", "Line on floor", "Altimeter"], "correct": 2, "correct_section": "9.6.2.1.1"},
            {"id": 25, "question": "The videographer on an all-women 4-Way Open team may be what?", "options": ["Female only", "Male only", "Either sex", "Must be rated judge"], "correct": 2, "correct_section": "9.3.2.2"},
        ]
    },
    "ch9_national": {
        "name": "Chapter 9: Formation Skydiving - National Test",
        "chapter": "9",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "When 4-Way exit altitude is lowered for weather, what is the reduced working time?", "options": ["15 seconds", "20 seconds", "25 seconds", "30 seconds"], "correct": 1, "correct_section": "9.5.6.4.2"},
            {"id": 2, "question": "What is the reduced exit altitude for 4-Way FS in bad weather?", "options": ["6,500 feet", "7,000 feet", "7,500 feet", "8,000 feet"], "correct": 2, "correct_section": "9.5.6.4.2"},
            {"id": 3, "question": "What is the reduced working time for 8-Way at lower altitude?", "options": ["25 seconds", "30 seconds", "35 seconds", "40 seconds"], "correct": 1, "correct_section": "9.5.6.4.2"},
            {"id": 4, "question": "What is the reduced exit altitude for 8-Way in weather?", "options": ["8,000 feet", "8,500 feet", "9,000 feet", "10,000 feet"], "correct": 2, "correct_section": "9.5.6.4.2"},
            {"id": 5, "question": "What is the reduced working time for 16-Way at lower altitude?", "options": ["25 seconds", "30 seconds", "35 seconds", "40 seconds"], "correct": 1, "correct_section": "9.5.6.4.2"},
            {"id": 6, "question": "How many gold medalists from that class are allowed on Advanced/Intermediate 4-way teams?", "options": ["None", "One", "Two", "Three"], "correct": 1, "correct_section": "9.3"},
            {"id": 7, "question": "How many gold medalists are allowed on Advanced/Intermediate 8-way teams?", "options": ["Two", "Three", "Four", "Five"], "correct": 2, "correct_section": "9.3"},
            {"id": 8, "question": "For how many prior calendar years does the medal restriction apply?", "options": ["Three", "Four", "Five", "Six"], "correct": 2, "correct_section": "9.3"},
            {"id": 9, "question": "In 4-Way VFS Advanced draw, which blocks are excluded?", "options": ["1,2,3", "5,6,10,15,19", "All blocks included", "Only randoms used"], "correct": 1, "correct_section": "9.4.2.1.4"},
            {"id": 10, "question": "What round is assigned formation 8 (Star) in 10-Way?", "options": ["Round 1", "Round 5", "Round 6", "Tie-break"], "correct": 2, "correct_section": "9.4.2.1.9"},
            {"id": 11, "question": "In 10-Way, each team member must present what before formation completion?", "options": ["Grip check", "Individual separation", "Wave off", "Track"], "correct": 1, "correct_section": "9.6.2.2"},
            {"id": 12, "question": "How many members minimum must remain on a 16-Way team?", "options": ["Thirteen", "Fourteen", "Fifteen", "Sixteen"], "correct": 2, "correct_section": "9.3.4.1"},
            {"id": 13, "question": "How many members minimum must remain on a 10-Way team?", "options": ["Eight", "Nine", "Ten", "Eleven"], "correct": 1, "correct_section": "9.3.5.1"},
            {"id": 14, "question": "If both inter and second formation in a block are omitted, how many omissions count?", "options": ["Zero", "One", "Two", "Three"], "correct": 1, "correct_section": "9.7.1.2"},
            {"id": 15, "question": "If infringement in scoring formation carries into inter, how many infringements count?", "options": ["Zero", "One", "Two", "Depends on intent"], "correct": 1, "correct_section": "9.7.1.3"},
            {"id": 16, "question": "Total separation requires all competitors show no contact with what?", "options": ["Grips only", "Arms and grips", "Any body part", "Equipment"], "correct": 1, "correct_section": "9.8.9.1"},
            {"id": 17, "question": "A foot grip must be on or below what?", "options": ["Knee", "Calf", "Anklebone", "Toe"], "correct": 2, "correct_section": "9.8.2"},
            {"id": 18, "question": "Where possible, Meet Director will schedule rounds when sun is not within how many degrees of zenith?", "options": ["10 degrees", "15 degrees", "20 degrees", "30 degrees"], "correct": 2, "correct_section": "9.5.1.4"},
            {"id": 19, "question": "For 10-Way, what is the maximum score if no clear exit is shown?", "options": ["30 seconds", "35 seconds", "40 seconds", "DNF"], "correct": 1, "correct_section": "9.5.4.2"},
            {"id": 20, "question": "Mirror images of random formations are permitted.", "options": ["True for all events", "False for all events", "Only 10-Way", "Only 4-Way"], "correct": 0, "correct_section": "9.5.4.5"},
            {"id": 21, "question": "How many rounds are drawn including tie-breaker?", "options": ["Scheduled rounds only", "Scheduled plus one", "Scheduled plus two", "Double scheduled"], "correct": 1, "correct_section": "9.4.2.2.4"},
            {"id": 22, "question": "What happens if duplicate random/block is drawn within a single round?", "options": ["Stands", "Put back and redraw", "Skip that formation", "Use alternate"], "correct": 1, "correct_section": "9.4.2.2.3"},
            {"id": 23, "question": "Reduced exit altitude for 2-Way MFS and 4-Way VFS in weather is what?", "options": ["8,000 feet", "8,500 feet", "9,000 feet", "10,000 feet"], "correct": 2, "correct_section": "9.5.6.4.2"},
            {"id": 24, "question": "What is the reduced working time for 2-Way MFS and 4-Way VFS at lower altitude?", "options": ["15 seconds", "20 seconds", "25 seconds", "30 seconds"], "correct": 1, "correct_section": "9.5.6.4.2"},
            {"id": 25, "question": "Reduced exit altitude for 10-Way in weather is what?", "options": ["7,500 feet", "8,000 feet", "8,500 feet", "9,000 feet"], "correct": 2, "correct_section": "9.5.6.4.2"},
        ]
    },
    "ch10_regional": {
        "name": "Chapter 10: Canopy Formation - Regional Test",
        "chapter": "10",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "What is the exit altitude for 2-Way Sequential CF?", "options": ["7,000 feet", "8,000 feet", "9,000 feet", "10,000 feet"], "correct": 1, "correct_section": "10.3.1.1"},
            {"id": 2, "question": "What is the exit altitude for 4-Way Rotation CF?", "options": ["8,000 feet", "8,500 feet", "9,000 feet", "10,000 feet"], "correct": 2, "correct_section": "10.3.2.1"},
            {"id": 3, "question": "What is the exit altitude for 4-Way Sequential CF?", "options": ["8,500 feet", "9,000 feet", "9,500 feet", "10,000 feet"], "correct": 3, "correct_section": "10.3.3.1"},
            {"id": 4, "question": "What is the working time for 2-Way Sequential CF?", "options": ["90 seconds", "105 seconds", "120 seconds", "135 seconds"], "correct": 2, "correct_section": "10.3.1.2"},
            {"id": 5, "question": "What is the working time for 4-Way Rotation CF?", "options": ["105 seconds", "120 seconds", "135 seconds", "150 seconds"], "correct": 1, "correct_section": "10.3.2.2"},
            {"id": 6, "question": "What is the working time for 4-Way Sequential CF?", "options": ["105 seconds", "120 seconds", "135 seconds", "150 seconds"], "correct": 2, "correct_section": "10.3.3.2"},
            {"id": 7, "question": "How many rounds maximum are scheduled for 2-Way Sequential?", "options": ["Six", "Eight", "Ten", "Twelve"], "correct": 1, "correct_section": "10.4.1"},
            {"id": 8, "question": "How many rounds maximum are scheduled for 4-Way events?", "options": ["Six", "Eight", "Ten", "Twelve"], "correct": 1, "correct_section": "10.4.2"},
            {"id": 9, "question": "What is the maximum ground wind speed for CF events?", "options": ["7 m/s", "9 m/s", "11 m/s", "13 m/s"], "correct": 2, "correct_section": "10.7.1"},
            {"id": 10, "question": "How many points are deducted for each omission in CF?", "options": ["One", "Two", "Three", "Four"], "correct": 2, "correct_section": "10.5.2"},
            {"id": 11, "question": "What is the minimum score for any round in CF?", "options": ["Negative one", "Zero", "One", "Two"], "correct": 1, "correct_section": "10.5.3"},
            {"id": 12, "question": "How many principal judges minimum for 2-Way CF events?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "10.6.1"},
            {"id": 13, "question": "How many principal judges minimum for 4-Way CF events?", "options": ["Three", "Four", "Five", "Six"], "correct": 2, "correct_section": "10.6.2"},
            {"id": 14, "question": "A 2-Way CF team may have up to how many total members?", "options": ["Two", "Three", "Four", "Five"], "correct": 2, "correct_section": "10.2.1.1"},
            {"id": 15, "question": "A 4-Way CF team may have up to how many total members?", "options": ["Four", "Five", "Six", "Seven"], "correct": 2, "correct_section": "10.2.2.1"},
            {"id": 16, "question": "What constitutes a valid grip in CF?", "options": ["Any contact", "Line contact only", "Stationary contact on lines, canopy, or harness", "Grabbing risers"], "correct": 2, "correct_section": "10.5.5"},
            {"id": 17, "question": "What score is given for a grip taken during rotation that is not part of the sequence?", "options": ["No penalty", "Omission", "Point deducted", "Infringement"], "correct": 3, "correct_section": "10.5.6"},
            {"id": 18, "question": "The CF competition will be judged by ground-to-air video.", "options": ["True", "False", "Only for 4-Way", "Only for 2-Way"], "correct": 0, "correct_section": "10.6.3"},
            {"id": 19, "question": "What is the minimum number of members for a 2-Way team to continue?", "options": ["One", "Two", "One plus alternate", "Two plus alternate"], "correct": 1, "correct_section": "10.2.1.1"},
            {"id": 20, "question": "What is the minimum number of members for a 4-Way team to continue?", "options": ["Two", "Three", "Four", "Three plus alternate"], "correct": 2, "correct_section": "10.2.2.1"},
            {"id": 21, "question": "In 4-Way Rotation, what must each team member complete?", "options": ["One rotation", "One rotation in each slot", "Two rotations", "Full sequence"], "correct": 1, "correct_section": "10.1.2.2"},
            {"id": 22, "question": "Working time in CF starts when?", "options": ["First exit", "First canopy open", "First grip taken", "First formation complete"], "correct": 0, "correct_section": "10.3.1.3"},
            {"id": 23, "question": "How many formations are in each 2-Way Sequential round?", "options": ["Three or four", "Four or five", "Five or six", "Six or seven"], "correct": 1, "correct_section": "10.1.1.1"},
            {"id": 24, "question": "How many formations are in each 4-Way Sequential round?", "options": ["Three or four", "Four or five", "Five or six", "Six or seven"], "correct": 1, "correct_section": "10.1.3.1"},
            {"id": 25, "question": "Handholds on what are not permitted in CF?", "options": ["Lines only", "Canopy only", "Other competitors' bodies", "Risers only"], "correct": 2, "correct_section": "10.5.5.1"},
        ]
    },
    "ch10_national": {
        "name": "Chapter 10: Canopy Formation - National Test",
        "chapter": "10",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "In 4-Way Rotation, a team receives how many points for each correctly completed rotation?", "options": ["One", "Two", "Three", "Four"], "correct": 0, "correct_section": "10.5.1.2"},
            {"id": 2, "question": "A rotation is complete when all formation grips are taken and the team is what?", "options": ["Moving", "Stationary", "Level", "Descending"], "correct": 1, "correct_section": "10.5.1.3"},
            {"id": 3, "question": "What happens if a team member misses their slot in 4-Way Rotation?", "options": ["Continue anyway", "Omission penalty", "Round invalid", "Rejump offered"], "correct": 1, "correct_section": "10.5.1.4"},
            {"id": 4, "question": "The 2-Way CF team is eliminated if cut to how many members?", "options": ["Zero", "One", "One plus camera", "Two"], "correct": 1, "correct_section": "10.2.1.1"},
            {"id": 5, "question": "The 4-Way CF team is eliminated if cut to how many members?", "options": ["Two", "Three", "Three plus camera", "Four"], "correct": 1, "correct_section": "10.2.2.1"},
            {"id": 6, "question": "In tied placing for CF, how is it resolved?", "options": ["Tie-break round", "Highest single round", "Last round score", "Co-placing"], "correct": 0, "correct_section": "10.8.1"},
            {"id": 7, "question": "If tie persists after tie-break round in CF, what happens?", "options": ["Another round", "Best single round", "Average score", "Co-placing"], "correct": 3, "correct_section": "10.8.2"},
            {"id": 8, "question": "Aircraft speed at exit for CF must not exceed what?", "options": ["80 knots", "87 knots", "90 knots", "100 knots"], "correct": 1, "correct_section": "10.6.5"},
            {"id": 9, "question": "Ground-to-air camera position is determined by whom?", "options": ["Meet Director", "Chief Judge", "Video Controller", "Team"], "correct": 1, "correct_section": "10.6.4"},
            {"id": 10, "question": "What is the reduced exit altitude for 2-Way Sequential in weather?", "options": ["6,000 feet", "6,500 feet", "7,000 feet", "7,500 feet"], "correct": 2, "correct_section": "10.3.1.4"},
            {"id": 11, "question": "What is the reduced working time for 2-Way Sequential at lower altitude?", "options": ["75 seconds", "90 seconds", "100 seconds", "105 seconds"], "correct": 1, "correct_section": "10.3.1.4"},
            {"id": 12, "question": "What is the reduced exit altitude for 4-Way Rotation in weather?", "options": ["7,000 feet", "7,500 feet", "8,000 feet", "8,500 feet"], "correct": 1, "correct_section": "10.3.2.3"},
            {"id": 13, "question": "What is the reduced working time for 4-Way Rotation at lower altitude?", "options": ["75 seconds", "80 seconds", "90 seconds", "100 seconds"], "correct": 2, "correct_section": "10.3.2.3"},
            {"id": 14, "question": "What is the reduced exit altitude for 4-Way Sequential in weather?", "options": ["7,500 feet", "8,000 feet", "8,500 feet", "9,000 feet"], "correct": 1, "correct_section": "10.3.3.3"},
            {"id": 15, "question": "What is the reduced working time for 4-Way Sequential at lower altitude?", "options": ["90 seconds", "100 seconds", "105 seconds", "110 seconds"], "correct": 1, "correct_section": "10.3.3.3"},
            {"id": 16, "question": "Exit order for CF is determined by whom?", "options": ["Teams", "Meet Director", "Chief Judge", "Draw"], "correct": 2, "correct_section": "10.6.6"},
            {"id": 17, "question": "One complete round constitutes a meet in CF.", "options": ["True", "False", "Only for 2-Way", "Only for 4-Way"], "correct": 0, "correct_section": "10.4.1"},
            {"id": 18, "question": "Scores of all completed rounds are used to determine final standings.", "options": ["True", "False", "Only top half", "Drop lowest"], "correct": 0, "correct_section": "10.4.3"},
            {"id": 19, "question": "In 4-Way Rotation, the starting formation is what?", "options": ["Stack", "Stair-step", "Diamond", "Drawn formation"], "correct": 3, "correct_section": "10.1.2.1"},
            {"id": 20, "question": "After completing rotations in 4-Way Rotation, what happens?", "options": ["Round ends", "Sequence repeats", "Build exit formation", "Random formation"], "correct": 1, "correct_section": "10.1.2.3"},
            {"id": 21, "question": "How many formations are drawn for 4-Way Rotation per round?", "options": ["One", "Two", "Three", "Four"], "correct": 0, "correct_section": "10.1.2.1"},
            {"id": 22, "question": "CF working time ends when?", "options": ["Last grip released", "Time expires", "Break-off altitude", "Landing"], "correct": 1, "correct_section": "10.3.1.3"},
            {"id": 23, "question": "A penalty of what is given for formation not clearly presented to camera?", "options": ["Warning", "Infringement", "Omission", "Rejump required"], "correct": 1, "correct_section": "10.5.7"},
            {"id": 24, "question": "Ground video must show what for scoring to occur?", "options": ["Aircraft", "All canopies", "Formation and grips", "Target area"], "correct": 2, "correct_section": "10.6.3.1"},
            {"id": 25, "question": "Scoring formations must be presented to camera in what orientation?", "options": ["Vertical", "Horizontal", "Any orientation", "Formation-specific"], "correct": 2, "correct_section": "10.5.4"},
        ]
    },
    "ch11_regional": {
        "name": "Chapter 11: Artistic Events - Regional Test",
        "chapter": "11",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "What is the exit altitude for Freestyle?", "options": ["10,000 feet", "11,000 feet", "12,000 feet", "13,000 feet"], "correct": 3, "correct_section": "11.3.1.1"},
            {"id": 2, "question": "What is the exit altitude for Freefly?", "options": ["10,000 feet", "11,000 feet", "12,000 feet", "13,000 feet"], "correct": 3, "correct_section": "11.3.2.1"},
            {"id": 3, "question": "What is the working time for Freestyle?", "options": ["35 seconds", "40 seconds", "45 seconds", "50 seconds"], "correct": 2, "correct_section": "11.3.1.2"},
            {"id": 4, "question": "What is the working time for Freefly?", "options": ["35 seconds", "40 seconds", "45 seconds", "50 seconds"], "correct": 2, "correct_section": "11.3.2.2"},
            {"id": 5, "question": "A Freestyle team consists of how many members including videographer?", "options": ["Two", "Three", "Four", "Five"], "correct": 0, "correct_section": "11.2.1"},
            {"id": 6, "question": "A Freefly team consists of how many members including videographer?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "11.2.2"},
            {"id": 7, "question": "How many compulsory rounds are there in Freestyle?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "11.4.1.1"},
            {"id": 8, "question": "How many free rounds are there in Freestyle?", "options": ["Two", "Three", "Four", "Five"], "correct": 2, "correct_section": "11.4.1.2"},
            {"id": 9, "question": "How many compulsory rounds are there in Freefly?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "11.4.2.1"},
            {"id": 10, "question": "How many free rounds are there in Freefly?", "options": ["Two", "Three", "Four", "Five"], "correct": 2, "correct_section": "11.4.2.2"},
            {"id": 11, "question": "What is the maximum score for each compulsory move?", "options": ["5 points", "10 points", "15 points", "20 points"], "correct": 1, "correct_section": "11.5.1.1"},
            {"id": 12, "question": "What is the maximum score for execution in free rounds?", "options": ["5 points", "10 points", "15 points", "20 points"], "correct": 1, "correct_section": "11.5.2.1"},
            {"id": 13, "question": "What is the maximum score for presentation in Artistic Events?", "options": ["5 points", "10 points", "15 points", "20 points"], "correct": 1, "correct_section": "11.5.2.2"},
            {"id": 14, "question": "How many principal judges minimum for Artistic Events?", "options": ["Three", "Four", "Five", "Six"], "correct": 2, "correct_section": "11.6.1"},
            {"id": 15, "question": "The highest and lowest scores are dropped when calculating the average.", "options": ["True", "False", "Only in compulsory", "Only in free"], "correct": 0, "correct_section": "11.6.2"},
            {"id": 16, "question": "What is the maximum wind speed for Artistic Events?", "options": ["7 m/s", "9 m/s", "11 m/s", "13 m/s"], "correct": 2, "correct_section": "11.7.1"},
            {"id": 17, "question": "Aircraft speed at exit must not exceed what for AE?", "options": ["80 knots", "87 knots", "90 knots", "100 knots"], "correct": 1, "correct_section": "11.6.5"},
            {"id": 18, "question": "One complete round constitutes a meet for Artistic Events.", "options": ["True", "False", "Two rounds minimum", "Three rounds minimum"], "correct": 0, "correct_section": "11.4.3"},
            {"id": 19, "question": "Working time starts when for Artistic Events?", "options": ["First exit", "Videographer exit", "First performer exit", "First formation"], "correct": 2, "correct_section": "11.3.1.3"},
            {"id": 20, "question": "What happens if judges cannot determine start of working time in AE?", "options": ["Rejump", "Videographer exit used", "Average time applied", "Zero score"], "correct": 1, "correct_section": "11.3.1.3.1"},
            {"id": 21, "question": "A penalty of what percent is deducted if start time cannot be determined?", "options": ["10%", "15%", "20%", "25%"], "correct": 2, "correct_section": "11.3.1.3.2"},
            {"id": 22, "question": "Freestyle has how many performers?", "options": ["One", "Two", "Three", "Four"], "correct": 0, "correct_section": "11.2.1"},
            {"id": 23, "question": "Freefly has how many performers?", "options": ["One", "Two", "Three", "Four"], "correct": 1, "correct_section": "11.2.2"},
            {"id": 24, "question": "The maximum scheduled number of rounds for Artistic Events is what?", "options": ["Six", "Seven", "Eight", "Ten"], "correct": 1, "correct_section": "11.4.3"},
            {"id": 25, "question": "In tied placing, how is it resolved?", "options": ["Tie-break round", "Sum of free rounds", "Highest single round", "Co-placing"], "correct": 1, "correct_section": "11.8.1"},
        ]
    },
    "ch11_national": {
        "name": "Chapter 11: Artistic Events - National Test",
        "chapter": "11",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "If tie persists after comparing free rounds, what is compared next?", "options": ["Compulsory rounds", "Last free round", "Highest single round", "Average score"], "correct": 2, "correct_section": "11.8.2"},
            {"id": 2, "question": "If tie still persists, competitors are declared what?", "options": ["Co-placing", "Sudden death", "Tie-break jump", "Judges decide"], "correct": 0, "correct_section": "11.8.3"},
            {"id": 3, "question": "What is the reduced exit altitude for AE in weather?", "options": ["9,000 feet", "10,000 feet", "11,000 feet", "12,000 feet"], "correct": 1, "correct_section": "11.3.1.4"},
            {"id": 4, "question": "What is the reduced working time for AE at lower altitude?", "options": ["25 seconds", "30 seconds", "35 seconds", "40 seconds"], "correct": 2, "correct_section": "11.3.1.4"},
            {"id": 5, "question": "Compulsory sequences are drawn how far in advance?", "options": ["1 hour", "2 hours", "Day before", "Week before"], "correct": 1, "correct_section": "11.4.1.3"},
            {"id": 6, "question": "How many compulsory sequences are drawn per round?", "options": ["One", "Two", "Three", "Four"], "correct": 0, "correct_section": "11.4.1.1"},
            {"id": 7, "question": "Each compulsory sequence contains how many moves?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "11.4.1.1"},
            {"id": 8, "question": "In free rounds, what aspects are judged?", "options": ["Difficulty only", "Execution only", "Execution and presentation", "Difficulty, execution, presentation"], "correct": 2, "correct_section": "11.5.2"},
            {"id": 9, "question": "The maximum total score for a compulsory round is what?", "options": ["20 points", "30 points", "40 points", "50 points"], "correct": 1, "correct_section": "11.5.1.2"},
            {"id": 10, "question": "The maximum total score for a free round is what?", "options": ["10 points", "15 points", "20 points", "30 points"], "correct": 2, "correct_section": "11.5.2.3"},
            {"id": 11, "question": "How many judges' scores are used after dropping high and low?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "11.6.2"},
            {"id": 12, "question": "Freestyle compulsory moves must be performed in what order?", "options": ["Any order", "Drawn order", "Numerical order", "Difficulty order"], "correct": 1, "correct_section": "11.5.1.3"},
            {"id": 13, "question": "What happens if a compulsory move is omitted?", "options": ["Zero for round", "Zero for that move", "Penalty points", "Rejump"], "correct": 1, "correct_section": "11.5.1.4"},
            {"id": 14, "question": "Working time ends when for Artistic Events?", "options": ["Break-off signal", "Time expires", "First wave-off", "Landing"], "correct": 1, "correct_section": "11.3.1.2"},
            {"id": 15, "question": "Team is eliminated if cut to how many members in Freestyle?", "options": ["Zero", "One member total", "One performer", "No videographer"], "correct": 2, "correct_section": "11.2.1.1"},
            {"id": 16, "question": "Team is eliminated if cut to how many members in Freefly?", "options": ["Zero", "One", "One performer plus camera", "Two"], "correct": 1, "correct_section": "11.2.2.1"},
            {"id": 17, "question": "Execution scoring considers what aspects?", "options": ["Speed only", "Control and technique", "Originality", "Difficulty"], "correct": 1, "correct_section": "11.5.2.1.1"},
            {"id": 18, "question": "Presentation scoring considers what aspects?", "options": ["Speed and control", "Camera work and composition", "Difficulty only", "Formation only"], "correct": 1, "correct_section": "11.5.2.2.1"},
            {"id": 19, "question": "The videographer in Freestyle may be what?", "options": ["Performer only", "Dedicated camera only", "Either", "Must be third person"], "correct": 2, "correct_section": "11.2.1.2"},
            {"id": 20, "question": "Judges watch the video how many times at normal speed initially?", "options": ["Once", "Twice", "Three times", "Unlimited"], "correct": 0, "correct_section": "11.6.3"},
            {"id": 21, "question": "Additional viewings are allowed at what discretion?", "options": ["Team request", "Chief Judge", "Majority of judges", "Event Judge"], "correct": 1, "correct_section": "11.6.3.1"},
            {"id": 22, "question": "The dive pool for compulsory is maintained by whom?", "options": ["ISC", "USPA", "Chief Judge", "Competition Committee"], "correct": 0, "correct_section": "11.4.1.1"},
            {"id": 23, "question": "What happens if incomplete round cannot be finished from full altitude?", "options": ["Round cancelled", "Lower altitude used", "Scores stand", "Rejumps for all"], "correct": 1, "correct_section": "11.3.1.5"},
            {"id": 24, "question": "When teams jump from different altitudes in same round, rescoring uses what?", "options": ["Higher altitude time", "Lower altitude time", "Average time", "Original scores stand"], "correct": 1, "correct_section": "11.3.1.5.1"},
            {"id": 25, "question": "Freefly teams may have up to how many total members?", "options": ["Three", "Four", "Five", "Six"], "correct": 1, "correct_section": "11.2.2"},
        ]
    },
    "ch12_13_regional": {
        "name": "Chapters 12 & 13: Canopy Piloting - Regional Test",
        "chapter": "12-13",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "What is the exit altitude for Canopy Piloting?", "options": ["4,000 feet", "5,000 feet", "6,000 feet", "6,500 feet"], "correct": 1, "correct_section": "12.2.1"},
            {"id": 2, "question": "How many events comprise Canopy Piloting?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "12.1.1"},
            {"id": 3, "question": "What are the three CP events?", "options": ["Speed, Distance, Style", "Speed, Distance, Zone Accuracy", "Speed, Accuracy, Style", "Distance, Accuracy, Freestyle"], "correct": 1, "correct_section": "12.1.1.1"},
            {"id": 4, "question": "What is the minimum course length for Speed?", "options": ["50 meters", "60 meters", "70 meters", "80 meters"], "correct": 2, "correct_section": "12.3.1.1"},
            {"id": 5, "question": "What is the maximum ground wind speed for CP?", "options": ["5 m/s", "7 m/s", "9 m/s", "11 m/s"], "correct": 1, "correct_section": "12.7.1"},
            {"id": 6, "question": "How many judges minimum are required for CP?", "options": ["Five", "Six", "Seven", "Eight"], "correct": 3, "correct_section": "12.6.1"},
            {"id": 7, "question": "In Zone Accuracy, the maximum score per round is what?", "options": ["50 points", "75 points", "100 points", "125 points"], "correct": 2, "correct_section": "12.3.3.2"},
            {"id": 8, "question": "In Distance, scoring begins at what point?", "options": ["Exit point", "Entry gate", "Water contact", "Course start"], "correct": 1, "correct_section": "12.3.2.1"},
            {"id": 9, "question": "What is the width of the CP course?", "options": ["10 meters", "12 meters", "15 meters", "20 meters"], "correct": 2, "correct_section": "12.3.1.2"},
            {"id": 10, "question": "How many rounds maximum are scheduled for CP?", "options": ["Six", "Eight", "Ten", "Twelve"], "correct": 1, "correct_section": "12.4.1"},
            {"id": 11, "question": "One complete round constitutes a meet for CP.", "options": ["True", "False", "Two rounds", "Three rounds"], "correct": 0, "correct_section": "12.4.1"},
            {"id": 12, "question": "What happens if a competitor touches the water before the entry gate in Speed?", "options": ["Rejump", "Zero score", "Penalty points", "DNF"], "correct": 1, "correct_section": "12.3.1.4"},
            {"id": 13, "question": "The Overall standings are calculated using what?", "options": ["Total points", "Average placing", "Combined event scores", "Best three rounds"], "correct": 1, "correct_section": "12.8.1"},
            {"id": 14, "question": "Aircraft speed at exit for CP must not exceed what?", "options": ["80 knots", "87 knots", "90 knots", "100 knots"], "correct": 1, "correct_section": "12.6.4"},
            {"id": 15, "question": "CP-Freestyle is covered in which chapter?", "options": ["Chapter 12", "Chapter 13", "Chapter 14", "Appendix"], "correct": 1, "correct_section": "13.1.1"},
            {"id": 16, "question": "What is the exit altitude for CP-Freestyle?", "options": ["4,000 feet", "5,000 feet", "6,000 feet", "6,500 feet"], "correct": 1, "correct_section": "13.2.1"},
            {"id": 17, "question": "How many compulsory rounds in CP-Freestyle?", "options": ["One", "Two", "Three", "Four"], "correct": 1, "correct_section": "13.4.1.1"},
            {"id": 18, "question": "How many free rounds in CP-Freestyle?", "options": ["Two", "Three", "Four", "Five"], "correct": 2, "correct_section": "13.4.1.2"},
            {"id": 19, "question": "CP-Freestyle is an individual event.", "options": ["True", "False", "Team of two", "Team of three"], "correct": 0, "correct_section": "13.1.2"},
            {"id": 20, "question": "What is the maximum score for execution in CP-Freestyle free rounds?", "options": ["5 points", "10 points", "15 points", "20 points"], "correct": 1, "correct_section": "13.5.2.1"},
            {"id": 21, "question": "How many judges minimum for CP-Freestyle?", "options": ["Three", "Four", "Five", "Six"], "correct": 2, "correct_section": "13.6.1"},
            {"id": 22, "question": "In Speed, the course ends at what?", "options": ["Water exit", "Exit gate", "100-meter mark", "Landing"], "correct": 1, "correct_section": "12.3.1.3"},
            {"id": 23, "question": "What is dropped when calculating the average score in CP-Freestyle?", "options": ["Nothing", "Highest and lowest", "Lowest only", "Highest only"], "correct": 1, "correct_section": "13.6.2"},
            {"id": 24, "question": "The maximum wind speed for CP-Freestyle is what?", "options": ["5 m/s", "7 m/s", "9 m/s", "11 m/s"], "correct": 1, "correct_section": "13.7.1"},
            {"id": 25, "question": "How many rounds maximum are scheduled for CP-Freestyle?", "options": ["Five", "Six", "Seven", "Eight"], "correct": 1, "correct_section": "13.4.2"},
        ]
    },
    "ch12_13_national": {
        "name": "Chapters 12 & 13: Canopy Piloting - National Test",
        "chapter": "12-13",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "In Speed, time is measured to what precision?", "options": ["0.1 seconds", "0.01 seconds", "0.001 seconds", "0.0001 seconds"], "correct": 1, "correct_section": "12.3.1.5"},
            {"id": 2, "question": "In Distance, measurements are to what precision?", "options": ["0.1 meters", "0.5 meters", "1 meter", "0.01 meters"], "correct": 0, "correct_section": "12.3.2.3"},
            {"id": 3, "question": "In Zone Accuracy, the center zone is worth how many points?", "options": ["50 points", "75 points", "100 points", "125 points"], "correct": 2, "correct_section": "12.3.3.3"},
            {"id": 4, "question": "What is the penalty for going outside the course in Speed?", "options": ["Zero score", "5-second penalty", "DNF", "Rejump"], "correct": 0, "correct_section": "12.3.1.6"},
            {"id": 5, "question": "In Distance, what constitutes the measured distance?", "options": ["Entry to water exit", "Entry to exit gate", "Water contact to water exit", "Entry to landing"], "correct": 2, "correct_section": "12.3.2.2"},
            {"id": 6, "question": "How many zones are in Zone Accuracy?", "options": ["Three", "Four", "Five", "Six"], "correct": 2, "correct_section": "12.3.3.1"},
            {"id": 7, "question": "In CP tied placing, what is the first tiebreaker?", "options": ["Best single round", "Best event placing", "Overall points", "Speed result"], "correct": 0, "correct_section": "12.8.2"},
            {"id": 8, "question": "The host must provide how many additional persons to assist CP judges?", "options": ["One", "Two", "Three", "Four"], "correct": 1, "correct_section": "12.6.1.1"},
            {"id": 9, "question": "At least one helper must be able to operate what?", "options": ["Timing system", "Video judging system", "Wind meter", "Radio"], "correct": 1, "correct_section": "12.6.1.1"},
            {"id": 10, "question": "CP helpers should preferably have what rating?", "options": ["Regional FS judge", "National CP judge", "Local CP judge", "Any judge rating"], "correct": 2, "correct_section": "12.6.1.1"},
            {"id": 11, "question": "CP helpers must be approved by whom no later than day before OPP?", "options": ["Meet Director", "Chief Judge", "Video Controller", "USPA Controller"], "correct": 1, "correct_section": "12.6.1.1"},
            {"id": 12, "question": "What happens if competitor's body touches water before entry gate in Distance?", "options": ["Score counts", "Zero score", "Rejump", "Penalty meters"], "correct": 1, "correct_section": "12.3.2.4"},
            {"id": 13, "question": "In Zone Accuracy, the outermost zone is worth how many points?", "options": ["10 points", "15 points", "20 points", "25 points"], "correct": 2, "correct_section": "12.3.3.4"},
            {"id": 14, "question": "CP-Freestyle compulsory sequences contain how many moves?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "13.4.1.1"},
            {"id": 15, "question": "Maximum score for each compulsory move in CP-Freestyle?", "options": ["5 points", "10 points", "15 points", "20 points"], "correct": 1, "correct_section": "13.5.1.1"},
            {"id": 16, "question": "Maximum total score for CP-Freestyle compulsory round?", "options": ["20 points", "30 points", "40 points", "50 points"], "correct": 1, "correct_section": "13.5.1.2"},
            {"id": 17, "question": "Maximum score for presentation in CP-Freestyle free rounds?", "options": ["5 points", "10 points", "15 points", "20 points"], "correct": 1, "correct_section": "13.5.2.2"},
            {"id": 18, "question": "Maximum total score for CP-Freestyle free round?", "options": ["10 points", "15 points", "20 points", "30 points"], "correct": 2, "correct_section": "13.5.2.3"},
            {"id": 19, "question": "In CP-Freestyle tied placing, what is compared first?", "options": ["Compulsory rounds", "Sum of free rounds", "Best single round", "Last round"], "correct": 1, "correct_section": "13.8.1"},
            {"id": 20, "question": "In CP, competitors jump in what order in later rounds?", "options": ["Random", "Registration order", "Reverse standings", "Same order"], "correct": 2, "correct_section": "12.5.1"},
            {"id": 21, "question": "The CP water course minimum depth is what?", "options": ["0.3 meters", "0.5 meters", "0.75 meters", "1 meter"], "correct": 2, "correct_section": "12.3.1.7"},
            {"id": 22, "question": "In Speed, what triggers the timing system start?", "options": ["Exit signal", "Entry gate", "First water contact", "Competitor signal"], "correct": 1, "correct_section": "12.3.1.3"},
            {"id": 23, "question": "CP-Freestyle working time starts when?", "options": ["Aircraft exit", "Canopy deployment", "Entry to performance area", "First maneuver"], "correct": 2, "correct_section": "13.3.1"},
            {"id": 24, "question": "One complete round constitutes a meet for CP-Freestyle.", "options": ["True", "False", "Two rounds", "Three rounds"], "correct": 0, "correct_section": "13.4.2"},
            {"id": 25, "question": "What is the minimum number of high-performance landings for CP Open class?", "options": ["100 in 12 months", "150 in 12 months", "200 total", "500 total"], "correct": 1, "correct_section": "1.5.2.2"},
        ]
    },
    "ch14_regional": {
        "name": "Chapter 14: Wingsuit Flying - Regional Test",
        "chapter": "14",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "What is the exit altitude for Wingsuit Performance?", "options": ["10,000 feet", "11,000 feet", "12,000 feet", "12,500 feet"], "correct": 3, "correct_section": "14.3.1.1"},
            {"id": 2, "question": "What is the exit altitude for Wingsuit Acrobatic?", "options": ["10,000 feet", "11,000 feet", "12,000 feet", "12,500 feet"], "correct": 3, "correct_section": "14.3.2.1"},
            {"id": 3, "question": "How many events comprise Wingsuit Performance?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "14.1.1.1"},
            {"id": 4, "question": "What are the three Performance events?", "options": ["Speed, Time, Distance", "Speed, Distance, Time", "Distance, Speed, Altitude", "Time, Distance, Style"], "correct": 0, "correct_section": "14.1.1.1"},
            {"id": 5, "question": "Wingsuit Performance is an individual event.", "options": ["True", "False", "Team of two", "Team of three"], "correct": 0, "correct_section": "14.1.1.2"},
            {"id": 6, "question": "Wingsuit Acrobatic team size is how many including videographer?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "14.2.2.1"},
            {"id": 7, "question": "How many compulsory rounds in WS Acrobatic?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "14.4.2.1"},
            {"id": 8, "question": "How many free rounds in WS Acrobatic?", "options": ["Two", "Three", "Four", "Five"], "correct": 2, "correct_section": "14.4.2.2"},
            {"id": 9, "question": "What is the working time for WS Acrobatic?", "options": ["45 seconds", "50 seconds", "55 seconds", "60 seconds"], "correct": 3, "correct_section": "14.3.2.2"},
            {"id": 10, "question": "How many judges minimum for Wingsuit Performance?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "14.6.1.1"},
            {"id": 11, "question": "How many judges minimum for Wingsuit Acrobatic?", "options": ["Three", "Four", "Five", "Six"], "correct": 2, "correct_section": "14.6.1.2"},
            {"id": 12, "question": "What is the maximum wind speed for Wingsuit events?", "options": ["7 m/s", "9 m/s", "11 m/s", "13 m/s"], "correct": 2, "correct_section": "14.7.1"},
            {"id": 13, "question": "The Performance window is between what altitudes?", "options": ["10,000-6,000 feet", "10,000-5,500 feet", "9,000-5,000 feet", "8,000-4,000 feet"], "correct": 1, "correct_section": "14.3.1.2"},
            {"id": 14, "question": "How many rounds maximum are scheduled for WS Performance?", "options": ["Six", "Eight", "Ten", "Twelve"], "correct": 2, "correct_section": "14.4.1"},
            {"id": 15, "question": "How many rounds maximum are scheduled for WS Acrobatic?", "options": ["Six", "Seven", "Eight", "Ten"], "correct": 1, "correct_section": "14.4.2.3"},
            {"id": 16, "question": "One complete round constitutes a meet for Wingsuit events.", "options": ["True", "False", "Two rounds", "Three rounds"], "correct": 0, "correct_section": "14.4.3"},
            {"id": 17, "question": "Aircraft speed at exit for WS must not exceed what?", "options": ["80 knots", "87 knots", "90 knots", "100 knots"], "correct": 1, "correct_section": "14.6.4"},
            {"id": 18, "question": "In WS Performance, scores are recorded using what?", "options": ["Video", "Ground observers", "GPS/FlySight devices", "Timing gates"], "correct": 2, "correct_section": "14.5.1.1"},
            {"id": 19, "question": "The Speed task measures what?", "options": ["Ground speed", "Horizontal speed", "Vertical speed", "Total speed"], "correct": 0, "correct_section": "14.1.1.1.1"},
            {"id": 20, "question": "The Time task measures what?", "options": ["Total flight time", "Time in window", "Time to target", "Freefall time"], "correct": 1, "correct_section": "14.1.1.1.2"},
            {"id": 21, "question": "The Distance task measures what?", "options": ["Total distance", "Horizontal distance", "Vertical distance", "Ground track"], "correct": 1, "correct_section": "14.1.1.1.3"},
            {"id": 22, "question": "WS Acrobatic performers must be how many?", "options": ["One", "Two", "Three", "Four"], "correct": 1, "correct_section": "14.2.2.1"},
            {"id": 23, "question": "The highest and lowest scores are dropped in WS Acrobatic.", "options": ["True", "False", "Only compulsory", "Only free"], "correct": 0, "correct_section": "14.6.2"},
            {"id": 24, "question": "WS Performance Overall uses what calculation method?", "options": ["Total points", "Average placing", "Sum of percentages", "Best rounds"], "correct": 2, "correct_section": "14.8.1"},
            {"id": 25, "question": "A wingsuit is defined as a suit with what?", "options": ["Arm wings only", "Leg wing only", "Both arm and leg surfaces", "Inflatable cells"], "correct": 2, "correct_section": "14.1.2.1"},
        ]
    },
    "ch14_national": {
        "name": "Chapter 14: Wingsuit Flying - National Test",
        "chapter": "14",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "In WS Performance, what happens if GPS device fails?", "options": ["Rejump", "Zero score", "Average of other rounds", "DNF"], "correct": 0, "correct_section": "14.5.1.2"},
            {"id": 2, "question": "The Performance window top altitude is what MSL?", "options": ["10,000 feet", "Varies by DZ", "13,000 feet", "Fixed at 3000m"], "correct": 1, "correct_section": "14.3.1.2.1"},
            {"id": 3, "question": "The Performance window bottom altitude is what MSL?", "options": ["5,000 feet", "Varies by DZ", "6,000 feet", "Fixed at 1700m"], "correct": 1, "correct_section": "14.3.1.2.2"},
            {"id": 4, "question": "What is the reduced exit altitude for WS in weather?", "options": ["9,000 feet", "10,000 feet", "11,000 feet", "11,500 feet"], "correct": 1, "correct_section": "14.3.1.3"},
            {"id": 5, "question": "At reduced altitude, the window is adjusted by what?", "options": ["1,000 feet lower", "1,500 feet lower", "2,000 feet lower", "Same window"], "correct": 2, "correct_section": "14.3.1.3.1"},
            {"id": 6, "question": "WS Acrobatic compulsory sequences contain how many moves?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "14.4.2.1"},
            {"id": 7, "question": "Maximum score for each compulsory move in WS Acrobatic?", "options": ["5 points", "10 points", "15 points", "20 points"], "correct": 1, "correct_section": "14.5.2.1.1"},
            {"id": 8, "question": "Maximum total score for WS Acrobatic compulsory round?", "options": ["20 points", "30 points", "40 points", "50 points"], "correct": 1, "correct_section": "14.5.2.1.2"},
            {"id": 9, "question": "Maximum score for execution in WS Acrobatic free rounds?", "options": ["5 points", "10 points", "15 points", "20 points"], "correct": 1, "correct_section": "14.5.2.2.1"},
            {"id": 10, "question": "Maximum score for presentation in WS Acrobatic free rounds?", "options": ["5 points", "10 points", "15 points", "20 points"], "correct": 1, "correct_section": "14.5.2.2.2"},
            {"id": 11, "question": "Maximum total score for WS Acrobatic free round?", "options": ["10 points", "15 points", "20 points", "30 points"], "correct": 2, "correct_section": "14.5.2.2.3"},
            {"id": 12, "question": "Working time starts when for WS Acrobatic?", "options": ["First exit", "Last exit", "Videographer exit", "First performer exit"], "correct": 3, "correct_section": "14.3.2.3"},
            {"id": 13, "question": "A penalty of what percent is deducted if start time cannot be determined?", "options": ["10%", "15%", "20%", "25%"], "correct": 2, "correct_section": "14.3.2.3.2"},
            {"id": 14, "question": "In WS Performance tied placing, what is compared first?", "options": ["Best single round", "Sum of task scores", "Last round", "Speed score"], "correct": 0, "correct_section": "14.8.2"},
            {"id": 15, "question": "In WS Acrobatic tied placing, what is compared first?", "options": ["Compulsory rounds", "Sum of free rounds", "Best single round", "Last round"], "correct": 1, "correct_section": "14.8.3"},
            {"id": 16, "question": "WS Acrobatic team is eliminated if cut to how many performers?", "options": ["Zero", "One", "One plus camera", "Two"], "correct": 1, "correct_section": "14.2.2.1.1"},
            {"id": 17, "question": "WS Acrobatic team may have up to how many total members?", "options": ["Three", "Four", "Five", "Six"], "correct": 1, "correct_section": "14.2.2.1"},
            {"id": 18, "question": "Speed in WS Performance is measured in what units?", "options": ["mph", "knots", "km/h", "m/s"], "correct": 2, "correct_section": "14.5.1.1.1"},
            {"id": 19, "question": "Time in WS Performance is measured in what units?", "options": ["Milliseconds", "Centiseconds", "Seconds", "Minutes"], "correct": 2, "correct_section": "14.5.1.1.2"},
            {"id": 20, "question": "Distance in WS Performance is measured in what units?", "options": ["Feet", "Meters", "Kilometers", "Miles"], "correct": 1, "correct_section": "14.5.1.1.3"},
            {"id": 21, "question": "Position logging devices must be approved by whom?", "options": ["FAI", "USPA", "ISC", "Chief Judge"], "correct": 2, "correct_section": "14.5.1.1"},
            {"id": 22, "question": "Competitors must carry how many logging devices?", "options": ["One", "Two", "Three", "One primary, one backup"], "correct": 1, "correct_section": "14.5.1.3"},
            {"id": 23, "question": "If only one device records valid data, that score is used.", "options": ["True", "False", "Rejump required", "Zero score"], "correct": 0, "correct_section": "14.5.1.4"},
            {"id": 24, "question": "What happens if neither device records valid data?", "options": ["Zero score", "Average of others", "Rejump", "DNF"], "correct": 2, "correct_section": "14.5.1.5"},
            {"id": 25, "question": "WS Performance results are calculated using what?", "options": ["Raw scores", "Percentages of best", "Standard deviations", "Rankings only"], "correct": 1, "correct_section": "14.5.1.6"},
        ]
    },
    "ch15_regional": {
        "name": "Chapter 15: Speed Skydiving - Regional Test",
        "chapter": "15",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "What is the exit altitude for Speed Skydiving?", "options": ["12,000 feet", "13,000 feet", "14,000 feet", "15,000 feet"], "correct": 1, "correct_section": "15.3.1"},
            {"id": 2, "question": "Speed Skydiving is an individual event.", "options": ["True", "False", "Team of two", "Team of three"], "correct": 0, "correct_section": "15.1.2"},
            {"id": 3, "question": "How many rounds maximum are scheduled for Speed Skydiving?", "options": ["Six", "Eight", "Ten", "Twelve"], "correct": 1, "correct_section": "15.4.1"},
            {"id": 4, "question": "The Speed Skydiving window is between what altitudes?", "options": ["10,000-8,000 feet", "9,000-5,000 feet", "8,700-5,600 feet", "8,000-4,000 feet"], "correct": 2, "correct_section": "15.3.2"},
            {"id": 5, "question": "What is measured in Speed Skydiving?", "options": ["Ground speed", "Horizontal speed", "Vertical speed", "Total velocity"], "correct": 2, "correct_section": "15.1.1"},
            {"id": 6, "question": "Speed is measured using what devices?", "options": ["Video analysis", "Radar", "GPS/FlySight", "Timing gates"], "correct": 2, "correct_section": "15.5.1"},
            {"id": 7, "question": "How many judges minimum for Speed Skydiving?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "15.6.1"},
            {"id": 8, "question": "What is the maximum wind speed for Speed Skydiving?", "options": ["7 m/s", "9 m/s", "11 m/s", "13 m/s"], "correct": 2, "correct_section": "15.7.1"},
            {"id": 9, "question": "One complete round constitutes a meet for Speed Skydiving.", "options": ["True", "False", "Two rounds", "Three rounds"], "correct": 0, "correct_section": "15.4.2"},
            {"id": 10, "question": "Aircraft speed at exit must not exceed what?", "options": ["80 knots", "87 knots", "90 knots", "100 knots"], "correct": 1, "correct_section": "15.6.3"},
            {"id": 11, "question": "Speed is recorded in what units?", "options": ["mph", "knots", "km/h", "m/s"], "correct": 2, "correct_section": "15.5.2"},
            {"id": 12, "question": "Speed Skydiving competitors are ranked by what?", "options": ["Total speed", "Average speed", "Best single round", "Sum of rounds"], "correct": 1, "correct_section": "15.8.1"},
            {"id": 13, "question": "The window height is approximately how many feet?", "options": ["2,500 feet", "3,000 feet", "3,100 feet", "3,500 feet"], "correct": 2, "correct_section": "15.3.2.1"},
            {"id": 14, "question": "Competitors must carry how many logging devices?", "options": ["One", "Two", "Three", "Four"], "correct": 1, "correct_section": "15.5.3"},
            {"id": 15, "question": "What happens if only one device records valid data?", "options": ["Rejump", "Zero score", "That score used", "Average applied"], "correct": 2, "correct_section": "15.5.4"},
            {"id": 16, "question": "What happens if neither device records valid data?", "options": ["Zero score", "DNF", "Rejump", "Average of others"], "correct": 2, "correct_section": "15.5.5"},
            {"id": 17, "question": "In tied placing, what is compared first?", "options": ["Best single round", "Last round", "Total speed", "Number of valid rounds"], "correct": 0, "correct_section": "15.8.2"},
            {"id": 18, "question": "Position logging devices must be approved by whom?", "options": ["USPA", "FAI", "ISC", "Meet Director"], "correct": 2, "correct_section": "15.5.1"},
            {"id": 19, "question": "What is the minimum speed to qualify for team selection?", "options": ["350 kph", "400 kph", "450 kph", "500 kph"], "correct": 1, "correct_section": "4.3.1.3"},
            {"id": 20, "question": "Scores of all completed rounds are used for final standings.", "options": ["True", "False", "Drop lowest", "Best 6 of 8"], "correct": 0, "correct_section": "15.4.3"},
            {"id": 21, "question": "The window top altitude in meters is approximately what?", "options": ["2,500 m", "2,650 m", "2,700 m", "3,000 m"], "correct": 1, "correct_section": "15.3.2"},
            {"id": 22, "question": "The window bottom altitude in meters is approximately what?", "options": ["1,500 m", "1,700 m", "1,800 m", "2,000 m"], "correct": 1, "correct_section": "15.3.2"},
            {"id": 23, "question": "Mixed teams compete for separate medals.", "options": ["True", "False", "Only at Nationals", "Only at Worlds"], "correct": 0, "correct_section": "15.1.3"},
            {"id": 24, "question": "How many competitors form a mixed team?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "15.1.3.1"},
            {"id": 25, "question": "Mixed teams must include at least how many of each gender?", "options": ["One", "Two", "No requirement", "Equal numbers"], "correct": 0, "correct_section": "15.1.3.2"},
        ]
    },
    "general": {
        "name": "Chapters 1-3: General Competition Rules",
        "chapter": "1-3",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "What is the minimum number of freefall skydives required to compete at a USPA National Skydiving Championships?", "options": ["50 skydives", "75 skydives", "100 skydives", "200 skydives"], "correct": 2, "correct_section": "1.5.2.1"},
            {"id": 2, "question": "What is the minimum age requirement to compete at USPA Nationals?", "options": ["16 years", "17 years", "18 years", "21 years"], "correct": 2, "correct_section": "1.5.2.1"},
            {"id": 3, "question": "What is the maximum wind limit for all events unless otherwise specified?", "options": ["7 m/s", "9 m/s", "11 m/s", "13 m/s"], "correct": 2, "correct_section": "1.8.3.2"},
            {"id": 4, "question": "How long do competitors have to file a protest after knowledge of the grounds for protest?", "options": ["30 minutes", "1 hour", "2 hours", "24 hours"], "correct": 2, "correct_section": "1.8.4.2"},
            {"id": 5, "question": "What fee must accompany a protest?", "options": ["$25", "$50", "$75", "$100"], "correct": 1, "correct_section": "1.8.4.4"},
            {"id": 6, "question": "What is the minimum license required for Formation Skydiving Open class?", "options": ["A License", "B License", "C License", "D License"], "correct": 2, "correct_section": "Table 1"},
            {"id": 7, "question": "The Meet Director may NOT be a competitor in any event.", "options": ["True", "False", "Only in team events", "Only with Jury approval"], "correct": 0, "correct_section": "1.4.1.4"},
            {"id": 8, "question": "How many aircraft passes over the target are permitted per competitor or team for any jump?", "options": ["One", "Two", "Three", "Unlimited"], "correct": 1, "correct_section": "1.8.2.3.1"},
            {"id": 9, "question": "What is the minimum advance call time before boarding the aircraft?", "options": ["5 minutes only", "10 and 5 minutes", "15 and 5 minutes", "20 and 10 minutes"], "correct": 2, "correct_section": "1.7.5.1"},
            {"id": 10, "question": "For Open class Canopy Piloting, how many high-performance landings are required in the last 12 months?", "options": ["100 landings", "125 landings", "150 landings", "200 landings"], "correct": 2, "correct_section": "1.5.2.2"},
            {"id": 11, "question": "The panel of judges for a discipline must comprise an event judge plus at least how many other judges?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "1.4.2.4"},
            {"id": 12, "question": "What is the penalty for failure to meet video requirements at a USPA Nationals?", "options": ["Zero score", "10% score penalty", "20% score penalty", "Rejump required"], "correct": 2, "correct_section": "1.7.3.1"},
            {"id": 13, "question": "What is the minimum score required on the written exam for a Regional Judge rating?", "options": ["70%", "75%", "80%", "85%"], "correct": 1, "correct_section": "2.6.5.2"},
            {"id": 14, "question": "What is the minimum score required on the practical exam for a National Judge rating?", "options": ["75%", "80%", "85%", "90%"], "correct": 2, "correct_section": "2.6.5.3"},
            {"id": 15, "question": "How long is a USPA member required to have been a member before earning a National Judge rating?", "options": ["6 months", "1 year", "2 years", "3 years"], "correct": 1, "correct_section": "2.3.2.1"},
            {"id": 16, "question": "What is the initial judge rating fee that includes a logbook?", "options": ["$25", "$35", "$45", "$50"], "correct": 1, "correct_section": "2.3.5.1.2"},
            {"id": 17, "question": "A National Judge rating automatically expires at the end of which calendar year?", "options": ["Third year", "Fourth year", "Fifth year", "Seventh year"], "correct": 2, "correct_section": "2.5.1.2.1"},
            {"id": 18, "question": "By what date must judges contact the Director of Competition to be on the active judges list?", "options": ["October 1", "November 1", "December 1", "January 1"], "correct": 2, "correct_section": "2.5.2.1"},
            {"id": 19, "question": "To apply for Judge Examiner appointment, how many consecutive years must a judge be on the active list?", "options": ["Three years", "Four years", "Five years", "Seven years"], "correct": 2, "correct_section": "2.6.3.1"},
            {"id": 20, "question": "A Regional Judge's rating is valid for how long?", "options": ["1 year", "3 years", "5 years", "Permanent with USPA membership"], "correct": 3, "correct_section": "2.5.1.1.1"},
            {"id": 21, "question": "Who has authority to impose regulations due to unforeseeable exigencies during competition?", "options": ["Chief Judge only", "Meet Director only", "Meet Management", "The Jury"], "correct": 2, "correct_section": "1.6.3.1"},
            {"id": 22, "question": "What is the minimum number of judges required for Accuracy Landing?", "options": ["Three judges", "Four judges", "Five judges", "Six judges"], "correct": 2, "correct_section": "1.4.2.6"},
            {"id": 23, "question": "How many years can the same person serve as Chief Judge in the same discipline consecutively?", "options": ["One year", "Two years", "Three years", "No limit"], "correct": 1, "correct_section": "2.7.3.1.1"},
            {"id": 24, "question": "What minimum score on absolute assessments is required for FS and CF judge training?", "options": ["70%", "75%", "80%", "85%"], "correct": 2, "correct_section": "2.6.6.1"},
            {"id": 25, "question": "What organization delegated USPA authority over skydiving competition in the United States?", "options": ["FAA", "FAI", "NAA", "ISC"], "correct": 2, "correct_section": "1.1.3.1"},
        ]
    },
    "ch15_national": {
        "name": "Chapter 15: Speed Skydiving - National Test",
        "chapter": "15",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "What is the reduced exit altitude for SP in weather?", "options": ["10,000 feet", "11,000 feet", "12,000 feet", "12,500 feet"], "correct": 1, "correct_section": "15.3.3"},
            {"id": 2, "question": "At reduced altitude, the window is adjusted by what?", "options": ["500 feet", "1,000 feet", "1,500 feet", "2,000 feet"], "correct": 2, "correct_section": "15.3.3.1"},
            {"id": 3, "question": "If incomplete round cannot be finished from full altitude, what happens?", "options": ["Round cancelled", "Lower altitude used", "Scores stand", "Rejumps required"], "correct": 1, "correct_section": "15.3.4"},
            {"id": 4, "question": "When different altitudes used in same round, rescoring uses what window?", "options": ["Original", "Lower", "Average", "Higher"], "correct": 1, "correct_section": "15.3.4.1"},
            {"id": 5, "question": "For team selection, competitors must average at least what speed?", "options": ["350 kph", "400 kph", "450 kph", "500 kph"], "correct": 1, "correct_section": "4.3.1.3"},
            {"id": 6, "question": "The US Speed Team for World Championships contains up to how many members?", "options": ["Six", "Eight", "Ten", "Twelve"], "correct": 2, "correct_section": "4.3.2.9.1"},
            {"id": 7, "question": "How many male competitors are initially selected for the US Team?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "4.3.2.9.1"},
            {"id": 8, "question": "How many female competitors are initially selected for the US Team?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "4.3.2.9.1"},
            {"id": 9, "question": "Additional team slots are selected without regard to what?", "options": ["Speed", "Experience", "Gender", "Age"], "correct": 2, "correct_section": "4.3.2.9.1"},
            {"id": 10, "question": "The US Team for World Cup contains up to how many members?", "options": ["Eight", "Ten", "Twelve", "Fourteen"], "correct": 2, "correct_section": "4.3.2.9.2"},
            {"id": 11, "question": "Speed results are calculated to what precision?", "options": ["1 kph", "0.1 kph", "0.01 kph", "0.001 kph"], "correct": 2, "correct_section": "15.5.2.1"},
            {"id": 12, "question": "If both devices differ significantly, what happens?", "options": ["Average used", "Lower score", "Higher score", "Investigation"], "correct": 3, "correct_section": "15.5.6"},
            {"id": 13, "question": "What constitutes a significant difference between devices?", "options": ["5%", "10%", "15%", "20%"], "correct": 0, "correct_section": "15.5.6.1"},
            {"id": 14, "question": "The Chief Judge may order device inspection at any time.", "options": ["True", "False", "Only after complaint", "Only for top 3"], "correct": 0, "correct_section": "15.5.7"},
            {"id": 15, "question": "Device tampering results in what penalty?", "options": ["Warning", "Zero round", "Disqualification", "One-year ban"], "correct": 2, "correct_section": "15.5.8"},
            {"id": 16, "question": "The mixed team score is calculated how?", "options": ["Average of 3", "Sum of 3", "Best 2 of 3", "Weighted average"], "correct": 0, "correct_section": "15.8.3"},
            {"id": 17, "question": "For mixed team medals, teams are ranked by what?", "options": ["Total speed", "Average round speed", "Best round", "Individual rankings"], "correct": 1, "correct_section": "15.8.3.1"},
            {"id": 18, "question": "If tie persists in individual standings, competitors are declared what?", "options": ["Tie-break jump", "Co-placing", "Chief Judge decides", "Draw lots"], "correct": 1, "correct_section": "15.8.2.1"},
            {"id": 19, "question": "Competitors may wear any suit during Speed Skydiving.", "options": ["True", "False", "Only approved suits", "No wingsuits"], "correct": 3, "correct_section": "15.2.1"},
            {"id": 20, "question": "Speed suits must meet what requirement?", "options": ["No loose fabric", "Tight fit only", "Standard jumpsuit form", "FAI approved"], "correct": 2, "correct_section": "15.2.1.1"},
            {"id": 21, "question": "Lead weights are permitted in Speed Skydiving.", "options": ["True up to 10kg", "True up to 5kg", "False", "Only for training"], "correct": 2, "correct_section": "15.2.2"},
            {"id": 22, "question": "Exit order in later rounds is determined by what?", "options": ["Random", "Registration order", "Reverse standings", "Chief Judge"], "correct": 2, "correct_section": "15.4.4"},
            {"id": 23, "question": "The window height in meters is approximately what?", "options": ["900 m", "950 m", "1,000 m", "1,100 m"], "correct": 1, "correct_section": "15.3.2.1"},
            {"id": 24, "question": "Working time starts when for Speed Skydiving?", "options": ["Exit", "Window top", "Stable body position", "Device activation"], "correct": 1, "correct_section": "15.3.2.2"},
            {"id": 25, "question": "Working time ends when for Speed Skydiving?", "options": ["Window bottom", "Deployment", "Landing", "Device stop"], "correct": 0, "correct_section": "15.3.2.3"},
        ]
    },
}
