# USPA Judge Test Questions - All Chapters
# Each chapter has Regional (25 questions) and National (25 questions) tests

TESTS = {
    "ch8_regional": {
        "name": "Chapter 8: Accuracy Landing - Regional Test",
        "chapter": "AL",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "What is the diameter of the dead-center target on the AMD?", "options": ["1 cm", "2 cm", "3 cm", "5 cm"], "correct": 1, "correct_section": "8.1.3.1.1"},
            {"id": 2, "question": "What is the exit altitude for Individual Accuracy Landing?", "options": ["2,500 feet", "3,000 feet", "3,500 feet", "4,000 feet"], "correct": 1, "correct_section": "8.1.5.3"},
            {"id": 3, "question": "What is the exit altitude for Team Accuracy?", "options": ["3,000 feet", "3,500 feet", "4,000 feet", "4,500 feet"], "correct": 1, "correct_section": "8.1.5.4.1"},
            {"id": 4, "question": "What is the maximum scheduled number of rounds for Individual Accuracy Landing?", "options": ["Six", "Eight", "Ten", "Twelve"], "correct": 2, "correct_section": "8.1.6.1"},
            {"id": 5, "question": "What is the maximum scheduled number of rounds for Team Accuracy?", "options": ["Six", "Eight", "Ten", "Twelve"], "correct": 1, "correct_section": "8.1.6.2"},
            {"id": 6, "question": "At what wind speed must wind be monitored constantly and documented every 2 minutes?", "options": ["2 m/s", "3 m/s", "5 m/s", "6 m/s"], "correct": 1, "correct_section": "8.1.7.2"},
            {"id": 7, "question": "What is the range for maximum allowable wind speed set by officials?", "options": ["4-6 m/s", "5-7 m/s", "6-7.5 m/s", "7-9 m/s"], "correct": 2, "correct_section": "8.1.7.3"},
            {"id": 8, "question": "A landing off the AMD is scored as what distance?", "options": ["10 cm", "15 cm", "16 cm", "20 cm"], "correct": 2, "correct_section": "8.1.8.1.2"},
            {"id": 9, "question": "If a competitor lands on unreset AMD due to insufficient team separation, what score is given?", "options": ["10 cm", "15 cm", "16 cm", "Rejump"], "correct": 1, "correct_section": "8.1.8.2.3"},
            {"id": 10, "question": "How many principal judges are required at the target for Accuracy Landing?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "8.1.9.1"},
            {"id": 11, "question": "What is the radius of the marked circle the AMD must be centered within?", "options": ["10 meters", "15 meters", "20 meters", "25 meters"], "correct": 2, "correct_section": "8.1.10.3"},
            {"id": 12, "question": "What is the minimum thickness of the foam tuffet?", "options": ["20 cm", "25 cm", "30 cm", "35 cm"], "correct": 2, "correct_section": "8.1.10.3.2"},
            {"id": 13, "question": "What is the approximate diameter of the tuffet?", "options": ["3 meters", "4 meters", "5 meters", "6 meters"], "correct": 2, "correct_section": "8.1.10.3.2"},
            {"id": 14, "question": "What is the maximum aircraft speed at time of exit?", "options": ["80 knots", "87 knots", "95 knots", "100 knots"], "correct": 1, "correct_section": "8.1.12.2"},
            {"id": 15, "question": "What happens if the event is interrupted for 60 minutes or more?", "options": ["Competition cancelled", "WDI dropped", "Rejumps for all", "New draw required"], "correct": 1, "correct_section": "8.1.4.1"},
            {"id": 16, "question": "From what altitude is the Wind Drift Indicator dropped?", "options": ["2,000 feet", "2,500 feet", "3,000 feet", "3,500 feet"], "correct": 1, "correct_section": "8.1.4.1"},
            {"id": 17, "question": "The large wind indicator must respond to winds of at least what speed?", "options": ["1 m/s", "2 m/s", "3 m/s", "4 m/s"], "correct": 1, "correct_section": "8.1.10.1.1"},
            {"id": 18, "question": "How far from the target center is the large wind indicator positioned?", "options": ["30 meters", "40 meters", "50 meters", "60 meters"], "correct": 2, "correct_section": "8.1.10.1.1"},
            {"id": 19, "question": "What is the minimum horizontal diameter of footwear touching the target?", "options": ["0.5 cm", "1 cm", "1.5 cm", "2 cm"], "correct": 1, "correct_section": "8.1.11.2.1"},
            {"id": 20, "question": "At what ground wind speed is the event automatically interrupted?", "options": ["7 m/s", "8 m/s", "9 m/s", "10 m/s"], "correct": 2, "correct_section": "8.1.7.3.4"},
            {"id": 21, "question": "How long must scoring stop when wind exceeds the limit?", "options": ["15 seconds", "30 seconds", "45 seconds", "60 seconds"], "correct": 1, "correct_section": "8.1.7.3.2"},
            {"id": 22, "question": "Teams landing with fewer than four members receive what score for each missing member?", "options": ["10 cm", "15 cm", "16 cm", "20 cm"], "correct": 2, "correct_section": "8.1.8.2.6"},
            {"id": 23, "question": "What is the minimum number of rounds to constitute a meet for Individual Accuracy?", "options": ["One", "Two", "Three", "Four"], "correct": 0, "correct_section": "8.1.6.1"},
            {"id": 24, "question": "Within how many meters of the target is the wind direction streamer placed?", "options": ["10 meters", "15 meters", "20 meters", "25 meters"], "correct": 2, "correct_section": "8.1.10.1.2"},
            {"id": 25, "question": "What is the minimum height above ground for the wind-speed measuring device?", "options": ["4 meters", "5 meters", "6 meters", "8 meters"], "correct": 2, "correct_section": "8.1.10.2.2"},
        ]
    },
    "ch8_national": {
        "name": "Chapter 8: Accuracy Landing - National Test",
        "chapter": "AL",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "How much may the Meet Director lower Individual Accuracy exit altitude to negotiate weather?", "options": ["200 feet", "300 feet", "400 feet", "500 feet"], "correct": 1, "correct_section": "8.1.5.3"},
            {"id": 2, "question": "What is the lowest altitude Team Accuracy may be lowered to for weather?", "options": ["2,500 feet", "2,800 feet", "3,000 feet", "3,200 feet"], "correct": 1, "correct_section": "8.1.5.4.1"},
            {"id": 3, "question": "For how long is the target covered when ground wind exceeds 9 m/s?", "options": ["3 minutes", "5 minutes", "7 minutes", "10 minutes"], "correct": 1, "correct_section": "8.1.7.3.4"},
            {"id": 4, "question": "What is the maximum change in wind direction that triggers the limit when wind exceeds 3 m/s?", "options": ["45 degrees", "60 degrees", "90 degrees", "120 degrees"], "correct": 2, "correct_section": "8.1.7.5"},
            {"id": 5, "question": "A competitor landing within how many seconds after wind change is offered a rejump?", "options": ["15 seconds", "30 seconds", "45 seconds", "60 seconds"], "correct": 1, "correct_section": "8.1.7.5.1"},
            {"id": 6, "question": "During final approach, only principal judges are allowed within how many meters?", "options": ["3 meters", "5 meters", "7 meters", "10 meters"], "correct": 1, "correct_section": "8.1.9.4.1"},
            {"id": 7, "question": "The angle of footwear sole touching the target must be within what tolerance of 90 degrees?", "options": ["10 degrees", "15 degrees", "20 degrees", "25 degrees"], "correct": 1, "correct_section": "8.1.11.2.1"},
            {"id": 8, "question": "Who determines an erroneous AMD reading?", "options": ["Chief Judge alone", "Event Judge alone", "Simple majority of principal judges", "Unanimous judges"], "correct": 2, "correct_section": "8.1.13.1.1"},
            {"id": 9, "question": "A competitor with main canopy malfunction must signal by what method?", "options": ["Waving arms", "Arms and legs apart", "Spinning", "Pulling reserve immediately"], "correct": 1, "correct_section": "8.1.13.1.2"},
            {"id": 10, "question": "In Team Accuracy rounds 1-8, what is the jumping order?", "options": ["Teams then individuals", "Individuals then teams", "Alternating", "Random draw"], "correct": 1, "correct_section": "8.1.5.1"},
            {"id": 11, "question": "Rounds nine and ten of Accuracy are in what order?", "options": ["Team only", "Individual, reverse order of standing", "Individual, random order", "Team, reverse order"], "correct": 1, "correct_section": "8.1.5.2"},
            {"id": 12, "question": "How many jumpers may exit per pass in Individual Accuracy?", "options": ["One only", "One or two", "Up to three", "Up to four"], "correct": 1, "correct_section": "8.1.5.3"},
            {"id": 13, "question": "Who is responsible for selecting the proper exit point?", "options": ["Pilot", "Chief Judge", "Competitor/team", "Meet Director"], "correct": 2, "correct_section": "8.1.5.5"},
            {"id": 14, "question": "What happens to competitors waved off during halted jumping?", "options": ["Score counts", "16 cm score", "Must rejump", "Disqualified"], "correct": 2, "correct_section": "8.1.7.3.4"},
            {"id": 15, "question": "The AMD must be capable of measuring to what minimum distance?", "options": ["10 cm", "15 cm", "16 cm", "20 cm"], "correct": 2, "correct_section": "8.1.10.3.1"},
            {"id": 16, "question": "A competitor landing 15 seconds before wind exceeds limit and not scoring dead center is offered what?", "options": ["Score stands", "Rejump", "16 cm score", "Disqualification"], "correct": 1, "correct_section": "8.1.7.3.3"},
            {"id": 17, "question": "What must happen before the event continues after interruption due to winds aloft?", "options": ["5-minute wait", "New briefing", "New WDI dropped", "Equipment check"], "correct": 2, "correct_section": "8.1.9.9.3"},
            {"id": 18, "question": "Substitutes to team composition are permitted after competition begins.", "options": ["True", "False", "Only with CJ approval", "Only for injury"], "correct": 1, "correct_section": "8.1.3.2.2"},
            {"id": 19, "question": "What device must be used to alert judges of a wind hold?", "options": ["Radio", "Flag", "Audible device", "Light signal"], "correct": 2, "correct_section": "8.1.7.4"},
            {"id": 20, "question": "If canopy condition resulted from faulty equipment or improper judgment, what happens?", "options": ["Rejump awarded", "No rejump awarded", "Half score", "Disqualification"], "correct": 1, "correct_section": "8.1.13.1.2"},
            {"id": 21, "question": "For canopy conflict with own teammate, the team receives what?", "options": ["Rejump", "No rejump, score counts", "16 cm for affected", "Disqualification"], "correct": 1, "correct_section": "8.1.13.2.2"},
            {"id": 22, "question": "If AMD is defective or not reset and first contact was on it, what is offered?", "options": ["Score stands", "Rejump", "16 cm", "Dead center"], "correct": 1, "correct_section": "8.1.13.3"},
            {"id": 23, "question": "In case of tie in top three places, how many tie-break rounds maximum?", "options": ["One", "Two", "Three", "Unlimited"], "correct": 1, "correct_section": "8.2.2.3"},
            {"id": 24, "question": "Winds aloft refers to winds occurring above what?", "options": ["500 feet", "1000 feet", "Wind-speed device altitude", "Exit altitude"], "correct": 2, "correct_section": "8.A.1.2.8"},
            {"id": 25, "question": "The control pad when struck at any point scores what?", "options": ["10 cm", "15 cm", "16 cm", "Maximum"], "correct": 2, "correct_section": "8.A.1.2.3"},
        ]
    },
    "ch9_regional": {
        "name": "Chapter 9: Formation Skydiving - Regional Test",
        "chapter": "FS",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "What is the exit altitude for 4-Way Formation Skydiving?", "options": ["9,500 feet", "10,500 feet", "11,500 feet", "13,000 feet"], "correct": 1, "correct_section": "9.5.2.1"},
            {"id": 2, "question": "What is the working time for 4-Way FS?", "options": ["30 seconds", "35 seconds", "40 seconds", "50 seconds"], "correct": 1, "correct_section": "9.5.2.3"},
            {"id": 3, "question": "What is the exit altitude for 8-Way FS?", "options": ["10,500 feet", "11,000 feet", "12,000 feet", "13,000 feet"], "correct": 3, "correct_section": "9.5.3.1"},
            {"id": 4, "question": "What is the working time for 8-Way FS?", "options": ["35 seconds", "40 seconds", "45 seconds", "50 seconds"], "correct": 3, "correct_section": "9.5.3.3"},
            {"id": 5, "question": "How many points are deducted for each omission?", "options": ["One", "Two", "Three", "Four"], "correct": 2, "correct_section": "9.7.1.2"},
            {"id": 6, "question": "What is the minimum score for any round?", "options": ["Negative three", "Negative one", "Zero", "One"], "correct": 2, "correct_section": "9.7.1.4"},
            {"id": 7, "question": "What is the maximum scheduled number of rounds for 4-Way and 8-Way FS?", "options": ["Six", "Eight", "Ten", "Twelve"], "correct": 2, "correct_section": "9.4.3.3"},
            {"id": 8, "question": "What is the exit altitude for 2-Way MFS and 4-Way VFS?", "options": ["10,500 feet", "11,000 feet", "12,000 feet", "13,000 feet"], "correct": 3, "correct_section": "9.5.1.1"},
            {"id": 9, "question": "What is the working time for 2-Way MFS and 4-Way VFS?", "options": ["30 seconds", "35 seconds", "40 seconds", "50 seconds"], "correct": 1, "correct_section": "9.5.1.3"},
            {"id": 10, "question": "How many members minimum must remain on a 4-Way team to continue competition?", "options": ["Two", "Three", "Four", "Five"], "correct": 2, "correct_section": "9.3.2.1"},
            {"id": 11, "question": "How many members minimum must remain on an 8-Way team?", "options": ["Six", "Seven", "Eight", "Nine"], "correct": 2, "correct_section": "9.3.3.1"},
            {"id": 12, "question": "What is the exit altitude for 16-Way FS?", "options": ["11,000 feet", "12,000 feet", "13,000 feet", "14,000 feet"], "correct": 2, "correct_section": "9.5.5.1"},
            {"id": 13, "question": "What is the working time for 16-Way FS?", "options": ["35 seconds", "40 seconds", "45 seconds", "50 seconds"], "correct": 3, "correct_section": "9.5.5.3"},
            {"id": 14, "question": "What is the exit altitude for 10-Way FS?", "options": ["10,000 feet", "11,000 feet", "12,000 feet", "13,000 feet"], "correct": 1, "correct_section": "9.5.4.1"},
            {"id": 15, "question": "What is the total working time for 10-Way FS?", "options": ["35 seconds", "40 seconds", "45 seconds", "50 seconds"], "correct": 1, "correct_section": "9.5.4.4"},
            {"id": 16, "question": "10-Way formations must be held for a minimum of how many seconds?", "options": ["Three", "Four", "Five", "Six"], "correct": 2, "correct_section": "9.5.4.3"},
            {"id": 17, "question": "How much advance notice of draw results must teams receive before competition starts?", "options": ["One hour", "Two hours", "Three hours", "Four hours"], "correct": 1, "correct_section": "9.4.1.2"},
            {"id": 18, "question": "What penalty percentage is deducted if judges cannot determine start of working time?", "options": ["10%", "15%", "20%", "25%"], "correct": 2, "correct_section": "9.5.2.2.2"},
            {"id": 19, "question": "How many members maximum can a 4-Way team have including videographer?", "options": ["Four", "Five", "Six", "Seven"], "correct": 2, "correct_section": "9.3.2.1"},
            {"id": 20, "question": "How many members maximum can an 8-Way team have including videographer?", "options": ["Nine", "Ten", "Eleven", "Twelve"], "correct": 2, "correct_section": "9.3.3.1"},
            {"id": 21, "question": "What is the maximum scheduled number of rounds for 16-Way and 10-Way?", "options": ["Four", "Six", "Eight", "Ten"], "correct": 1, "correct_section": "9.4.3.4"},
            {"id": 22, "question": "4-Way exit altitude may be lowered to what for weather without working time change?", "options": ["8,500 feet", "9,000 feet", "9,500 feet", "10,000 feet"], "correct": 2, "correct_section": "9.5.2.1"},
            {"id": 23, "question": "A grip consists of contact between what and another jumper?", "options": ["Any body part", "Palm side of hand/fingers", "Fist", "Wrist"], "correct": 1, "correct_section": "9.8.2"},
            {"id": 24, "question": "For 10-Way, where must the videographer record an image before team exit?", "options": ["Target", "Aircraft door", "Line on floor", "Altimeter"], "correct": 2, "correct_section": "9.6.2.1.1"},
            {"id": 25, "question": "The videographer on an all-women 4-Way Open team may be what?", "options": ["Female only", "Male only", "Either sex", "Must be rated judge"], "correct": 2, "correct_section": "9.3.2.2"},
        ]
    },
    "ch9_national": {
        "name": "Chapter 9: Formation Skydiving - National Test",
        "chapter": "FS",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "When 4-Way exit altitude is lowered for weather, what is the reduced working time?", "options": ["15 seconds", "20 seconds", "25 seconds", "30 seconds"], "correct": 1, "correct_section": "9.5.6.4.2"},
            {"id": 2, "question": "What is the reduced exit altitude for 4-Way FS in bad weather?", "options": ["6,500 feet", "7,000 feet", "7,500 feet", "8,000 feet"], "correct": 2, "correct_section": "9.5.6.4.2"},
            {"id": 3, "question": "What is the reduced working time for 8-Way at lower altitude?", "options": ["25 seconds", "30 seconds", "35 seconds", "40 seconds"], "correct": 1, "correct_section": "9.5.6.4.2"},
            {"id": 4, "question": "What is the reduced exit altitude for 8-Way in weather?", "options": ["8,000 feet", "8,500 feet", "9,000 feet", "10,000 feet"], "correct": 2, "correct_section": "9.5.6.4.2"},
            {"id": 5, "question": "What is the reduced working time for 16-Way at lower altitude?", "options": ["25 seconds", "30 seconds", "35 seconds", "40 seconds"], "correct": 1, "correct_section": "9.5.6.4.2"},
            {"id": 6, "question": "How many gold medalists from that class are allowed on Advanced/Intermediate 4-way teams?", "options": ["None", "One", "Two", "Three"], "correct": 1, "correct_section": "9.3"},
            {"id": 7, "question": "How many gold medalists are allowed on Advanced/Intermediate 8-way teams?", "options": ["Two", "Three", "Four", "Five"], "correct": 2, "correct_section": "9.3"},
            {"id": 8, "question": "For how many prior calendar years does the medal restriction apply?", "options": ["Three", "Four", "Five", "Six"], "correct": 2, "correct_section": "9.3"},
            {"id": 9, "question": "In 4-Way VFS Advanced draw, which blocks are excluded?", "options": ["1,2,3", "5,6,10,15,19", "All blocks included", "Only randoms used"], "correct": 1, "correct_section": "9.4.2.1.4"},
            {"id": 10, "question": "What round is assigned formation 8 (Star) in 10-Way?", "options": ["Round 1", "Round 5", "Round 6", "Tie-break"], "correct": 2, "correct_section": "9.4.2.1.9"},
            {"id": 11, "question": "In 10-Way, each team member must present what before formation completion?", "options": ["Grip check", "Individual separation", "Wave off", "Track"], "correct": 1, "correct_section": "9.6.2.2"},
            {"id": 12, "question": "How many members minimum must remain on a 16-Way team?", "options": ["Thirteen", "Fourteen", "Fifteen", "Sixteen"], "correct": 3, "correct_section": "9.3.4.1"},
            {"id": 13, "question": "How many members minimum must remain on a 10-Way team?", "options": ["Eight", "Nine", "Ten", "Eleven"], "correct": 2, "correct_section": "9.3.5.1"},
            {"id": 14, "question": "If both inter and second formation in a block are omitted, how many omissions count?", "options": ["Zero", "One", "Two", "Three"], "correct": 1, "correct_section": "9.7.1.2"},
            {"id": 15, "question": "If infringement in scoring formation carries into inter, how many infringements count?", "options": ["Zero", "One", "Two", "Depends on intent"], "correct": 1, "correct_section": "9.7.1.3"},
            {"id": 16, "question": "Total separation requires all competitors show no contact with what?", "options": ["Grips only", "Arms and grips", "Any body part", "Equipment"], "correct": 1, "correct_section": "9.8.9.1"},
            {"id": 17, "question": "A foot grip must be on or below what?", "options": ["Knee", "Calf", "Anklebone", "Toe"], "correct": 2, "correct_section": "9.8.2"},
            {"id": 18, "question": "Where possible, Meet Director will schedule rounds when sun is not within how many degrees of zenith?", "options": ["10 degrees", "15 degrees", "20 degrees", "30 degrees"], "correct": 2, "correct_section": "9.5.1.4"},
            {"id": 19, "question": "For 10-Way, what is the maximum score if no clear exit is shown?", "options": ["30 seconds", "35 seconds", "40 seconds", "DNF"], "correct": 1, "correct_section": "9.5.4.2"},
            {"id": 20, "question": "Mirror images of random formations are permitted.", "options": ["True for all events", "False for all events", "Only 10-Way", "Only 4-Way"], "correct": 0, "correct_section": "9.5.4.5"},
            {"id": 21, "question": "How many rounds are drawn including tie-breaker?", "options": ["Scheduled rounds only", "Scheduled plus one", "Scheduled plus two", "Double scheduled"], "correct": 1, "correct_section": "9.4.2.2.4"},
            {"id": 22, "question": "What happens if duplicate random/block is drawn within a single round?", "options": ["Stands", "Put back and redraw", "Skip that formation", "Use alternate"], "correct": 1, "correct_section": "9.4.2.2.3"},
            {"id": 23, "question": "Reduced exit altitude for 2-Way MFS and 4-Way VFS in weather is what?", "options": ["8,000 feet", "8,500 feet", "9,000 feet", "10,000 feet"], "correct": 2, "correct_section": "9.5.6.4.2"},
            {"id": 24, "question": "What is the reduced working time for 2-Way MFS and 4-Way VFS at lower altitude?", "options": ["15 seconds", "20 seconds", "25 seconds", "30 seconds"], "correct": 1, "correct_section": "9.5.6.4.2"},
            {"id": 25, "question": "Reduced exit altitude for 10-Way in weather is what?", "options": ["7,500 feet", "8,000 feet", "8,500 feet", "9,000 feet"], "correct": 2, "correct_section": "9.5.6.4.2"},
        ]
    },
    "ch10_regional": {
        "name": "Chapter 10: Canopy Formation - Regional Test",
        "chapter": "CF",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "What is the exit altitude for 2-Way Sequential CF?", "options": ["7,000 feet", "8,000 feet", "9,000 feet", "10,000 feet"], "correct": 1, "correct_section": "5.3.1"},
            {"id": 2, "question": "What is the exit altitude for 4-Way Rotation CF?", "options": ["8,000 feet", "8,500 feet", "9,000 feet", "10,000 feet"], "correct": 2, "correct_section": "5.1.1"},
            {"id": 3, "question": "What is the exit altitude for 4-Way Sequential CF?", "options": ["8,500 feet", "9,000 feet", "9,500 feet", "10,000 feet"], "correct": 3, "correct_section": "5.2.1"},
            {"id": 4, "question": "What is the working time for 2-Way Sequential CF?", "options": ["45 seconds", "60 seconds", "75 seconds", "90 seconds"], "correct": 1, "correct_section": "5.6.3.1"},
            {"id": 5, "question": "What is the working time for 4-Way Rotation CF?", "options": ["75 seconds", "90 seconds", "105 seconds", "120 seconds"], "correct": 1, "correct_section": "5.6.4.1"},
            {"id": 6, "question": "What is the working time for 4-Way Sequential CF?", "options": ["90 seconds", "105 seconds", "120 seconds", "135 seconds"], "correct": 2, "correct_section": "5.6.2.1"},
            {"id": 7, "question": "How many rounds maximum are scheduled for 2-Way Sequential?", "options": ["Six", "Eight", "Ten", "Twelve"], "correct": 1, "correct_section": "5.8.1"},
            {"id": 8, "question": "How many rounds maximum are scheduled for 4-Way events?", "options": ["Six", "Eight", "Ten", "Twelve"], "correct": 1, "correct_section": "5.8.1"},
            {"id": 9, "question": "What is the maximum ground wind speed for CF events?", "options": ["7 m/s", "9 m/s", "11 m/s", "13 m/s"], "correct": 1, "correct_section": "7.8.1"},
            {"id": 10, "question": "How many points are deducted as penalty for each omission in 4-Way Sequential CF?", "options": ["One", "Two", "Three", "Four"], "correct": 0, "correct_section": "7.3.3.1"},
            {"id": 11, "question": "How many points penalty for omission in 2-Way Sequential CF?", "options": ["One", "Two", "Three", "Four"], "correct": 1, "correct_section": "7.4.3.1"},
            {"id": 12, "question": "All forms of CF activity must cease by what altitude?", "options": ["2,000 feet", "2,500 feet", "3,000 feet", "3,500 feet"], "correct": 1, "correct_section": "5.7.1"},
            {"id": 13, "question": "The Meet Director may disqualify a team for breaching the break-off altitude rule.", "options": ["True", "False", "Only with warning", "Only at Nationals"], "correct": 0, "correct_section": "5.7.2"},
            {"id": 14, "question": "A 2-Way CF team may have up to how many total members?", "options": ["Two", "Three", "Four", "Five"], "correct": 2, "correct_section": "3.2.1"},
            {"id": 15, "question": "A 4-Way CF team may have up to how many total members?", "options": ["Four", "Five", "Six", "Seven"], "correct": 2, "correct_section": "3.1.1"},
            {"id": 16, "question": "What constitutes a valid grip in CF?", "options": ["Any contact", "A lines or front risers", "Any line contact", "Harness contact"], "correct": 1, "correct_section": "6.1.2"},
            {"id": 17, "question": "What score is given for a grip taken during rotation that is not part of the sequence?", "options": ["No penalty", "Omission", "Point deducted", "Infringement"], "correct": 3, "correct_section": "6.1.9"},
            {"id": 18, "question": "The CF competition will be judged by air-to-air video.", "options": ["True", "False", "Only for 4-Way", "Only for 2-Way"], "correct": 0, "correct_section": "7.6.1"},
            {"id": 19, "question": "What is the minimum number of members for a 2-Way team to continue?", "options": ["One", "Two", "Three (including videographer)", "Two plus alternate"], "correct": 2, "correct_section": "3.2.1"},
            {"id": 20, "question": "What is the minimum number of members for a 4-Way team to continue?", "options": ["Two", "Three", "Four", "Four plus videographer"], "correct": 3, "correct_section": "3.1.1"},
            {"id": 21, "question": "In 4-Way Rotation, rotations are made by which competitor?", "options": ["Any competitor", "The top competitor", "The bottom competitor", "Alternating competitors"], "correct": 1, "correct_section": "2.1.1.1"},
            {"id": 22, "question": "Working time in CF starts when?", "options": ["First exit", "First grip release from first formation", "First canopy open", "All canopies open"], "correct": 1, "correct_section": "5.6.1"},
            {"id": 23, "question": "How many formations are in each 2-Way Sequential round?", "options": ["Three", "Four", "Five", "Six"], "correct": 2, "correct_section": "4.2.2.1"},
            {"id": 24, "question": "How many formations are in each 4-Way Sequential round?", "options": ["Three or four", "Four or five", "Five or six", "Six or seven"], "correct": 1, "correct_section": "4.2.1.3"},
            {"id": 25, "question": "Handholds on what are not permitted in CF?", "options": ["Lines only", "Canopy only", "Other competitors' bodies", "Risers only"], "correct": 2, "correct_section": "6.1.2"},
        ]
    },
    "ch10_national": {
        "name": "Chapter 10: Canopy Formation - National Test",
        "chapter": "CF",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "In 4-Way Rotation, a team receives how many points for each correctly completed formation?", "options": ["One", "Two", "Three", "Four"], "correct": 0, "correct_section": "7.2.2"},
            {"id": 2, "question": "A 4-way plane/stack formation is complete when all grips are taken correctly.", "options": ["True", "False", "Only for plane", "Only for stack"], "correct": 0, "correct_section": "7.2.2"},
            {"id": 3, "question": "Team members rotating before bottom member takes grip receive credit for that formation.", "options": ["True", "False", "Only in Sequential", "Only in Rotation"], "correct": 1, "correct_section": "7.2.3"},
            {"id": 4, "question": "The 2-Way CF team is eliminated if cut to how many members including videographer?", "options": ["One", "Two", "Two or fewer", "Three"], "correct": 2, "correct_section": "3.2.1"},
            {"id": 5, "question": "The 4-Way CF team is eliminated if cut to how many members plus videographer?", "options": ["Two", "Three", "Three or fewer", "Four"], "correct": 2, "correct_section": "3.1.1"},
            {"id": 6, "question": "In tied placing for CF, what is the first tie-breaking method?", "options": ["Tie-break round", "Highest single round", "Last round score", "Co-placing"], "correct": 0, "correct_section": "8.3.1.1"},
            {"id": 7, "question": "If tie persists after highest single round comparison, what is used next?", "options": ["Another round", "Highest score from last round backwards", "Average score", "Co-placing"], "correct": 1, "correct_section": "8.3.1.3"},
            {"id": 8, "question": "A variety or combination of aircraft may be used for CF competition.", "options": ["True", "False", "Only single type", "Only turbine"], "correct": 0, "correct_section": "7.7.1"},
            {"id": 9, "question": "The team is responsible for providing video evidence for judging purposes.", "options": ["True", "False", "Only at Nationals", "Only for 4-Way"], "correct": 0, "correct_section": "7.1.3.2"},
            {"id": 10, "question": "In weather, the Meet Director may raise exit altitude to no higher than what?", "options": ["8,000 feet", "9,000 feet", "10,000 feet", "11,000 feet"], "correct": 2, "correct_section": "7.8.2"},
            {"id": 11, "question": "Teams may refuse to jump in rain or turbulent conditions.", "options": ["True", "False", "Only with evidence", "Only at Nationals"], "correct": 0, "correct_section": "7.8.3"},
            {"id": 12, "question": "If a team aborts a jump twice for the same reason, what happens?", "options": ["Rejump offered", "Warning given", "Team doesn't jump that round", "Disqualification"], "correct": 2, "correct_section": "7.8.5"},
            {"id": 13, "question": "Practice of formations other than those specified for a jump results in what?", "options": ["Warning", "Point deduction", "Disqualification from competition", "Rejump"], "correct": 2, "correct_section": "7.1.1.1"},
            {"id": 14, "question": "CF cannot be practiced or scored using what type of parachute?", "options": ["Main only", "Reserve (auxiliary)", "Sport canopy", "Student canopy"], "correct": 1, "correct_section": "7.1.2"},
            {"id": 15, "question": "If a competitor is disqualified for a jump, they receive how many points?", "options": ["Zero", "One", "Average", "Previous round score"], "correct": 0, "correct_section": "7.1.4.1"},
            {"id": 16, "question": "Exit order for CF is determined by whom?", "options": ["Teams", "Meet management", "Chief Judge", "Draw"], "correct": 1, "correct_section": "4.3.1"},
            {"id": 17, "question": "The minimum number of rounds to constitute a meet in CF is what?", "options": ["One", "Two", "Three", "Four"], "correct": 0, "correct_section": "5.8.1"},
            {"id": 18, "question": "The result for each team is based on total points from all completed rounds.", "options": ["True", "False", "Only top half", "Drop lowest"], "correct": 0, "correct_section": "8.1.1"},
            {"id": 19, "question": "4-Way Rotation consists of successive 4-way stack-plane formations made by rotation.", "options": ["True", "False", "Only stack", "Only plane"], "correct": 0, "correct_section": "2.1.1"},
            {"id": 20, "question": "In 4-Way Rotation, the top competitor drops grips and flies to what position?", "options": ["Top", "Middle", "Bottom", "Side"], "correct": 2, "correct_section": "2.1.1.1"},
            {"id": 21, "question": "The intermediate formation in 4-Way Rotation is a correctly completed what?", "options": ["2-way stack", "3-way stack-plane", "4-way diamond", "2-way plane"], "correct": 1, "correct_section": "2.1.1.2"},
            {"id": 22, "question": "Working time for 4-Way Sequential is how many seconds?", "options": ["60 seconds", "90 seconds", "120 seconds", "150 seconds"], "correct": 2, "correct_section": "5.6.2.1"},
            {"id": 23, "question": "A formation not clearly presented is scored as what?", "options": ["Warning", "Infringement", "Omission", "Rejump required"], "correct": 1, "correct_section": "6.1.9.1"},
            {"id": 24, "question": "Video evidence must show what for scoring to occur?", "options": ["Aircraft", "All canopies", "Formation and grips", "Target area"], "correct": 2, "correct_section": "7.1.3.1"},
            {"id": 25, "question": "All CF activity must cease by what altitude with jumpers separated?", "options": ["2,000 feet", "2,500 feet", "3,000 feet", "3,500 feet"], "correct": 1, "correct_section": "5.7.1"},
        ]
    },
    "ch11_regional": {
        "name": "Chapter 11: Artistic Events - Regional Test",
        "chapter": "AE",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "What is the exit altitude for Artistic Events?", "options": ["10,000 feet", "11,000 feet", "12,000 feet", "13,000 feet"], "correct": 3, "correct_section": "1.2.3"},
            {"id": 2, "question": "Working time for Freestyle Skydiving terminates after how many seconds?", "options": ["40 seconds", "43 seconds", "45 seconds", "50 seconds"], "correct": 2, "correct_section": "1.1.7.1"},
            {"id": 3, "question": "Working time for Freeflying terminates after how many seconds?", "options": ["40 seconds", "43 seconds", "45 seconds", "50 seconds"], "correct": 1, "correct_section": "1.1.7.2"},
            {"id": 4, "question": "Only performances within working time are evaluated by judges.", "options": ["True", "False", "Depends on difficulty", "Chief Judge decides"], "correct": 0, "correct_section": "4.4.1"},
            {"id": 5, "question": "A Freestyle team consists of a performer and a videographer.", "options": ["True", "False", "Only at Nationals", "Three members"], "correct": 0, "correct_section": "3.1.1"},
            {"id": 6, "question": "A Freefly team consists of how many Team Members?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "3.1.4"},
            {"id": 7, "question": "How many compulsory rounds are there in a full AE competition?", "options": ["Two", "Three", "Four", "Five"], "correct": 0, "correct_section": "3.3.2.1"},
            {"id": 8, "question": "How many free rounds are there in a full AE competition?", "options": ["Three", "Four", "Five", "Six"], "correct": 2, "correct_section": "3.3.2.2"},
            {"id": 9, "question": "The maximum scheduled number of rounds for Artistic Events is what?", "options": ["Five", "Six", "Seven", "Eight"], "correct": 2, "correct_section": "3.3.1"},
            {"id": 10, "question": "The round order for AE is F-C-F-F-C-F-F where C means what?", "options": ["Camera round", "Compulsory Routine", "Combined round", "Championship round"], "correct": 1, "correct_section": "3.3.4"},
            {"id": 11, "question": "Initial Difficulty Score for free routines ranges from 0.0 to what?", "options": ["5.0", "10.0", "15.0", "20.0"], "correct": 1, "correct_section": "4.2.1"},
            {"id": 12, "question": "Judges give a presentation score between 0.0 and what for free routines?", "options": ["5.0", "10.0", "15.0", "20.0"], "correct": 1, "correct_section": "4.2.3.1"},
            {"id": 13, "question": "For compulsory routines, judges score each sequence between 0.0 and what?", "options": ["5.0", "10.0", "15.0", "20.0"], "correct": 1, "correct_section": "4.3.1"},
            {"id": 14, "question": "A panel of how many judges evaluates AE routines?", "options": ["Three", "Four", "Five", "Six"], "correct": 0, "correct_section": "4.4.2.1"},
            {"id": 15, "question": "The three judges' scores are averaged to calculate the score.", "options": ["True", "False", "Only in compulsory", "Only in free"], "correct": 0, "correct_section": "4.5.2.1"},
            {"id": 16, "question": "What is the maximum wind speed for Artistic Events?", "options": ["7 m/s", "9 m/s", "11 m/s", "13 m/s"], "correct": 1, "correct_section": "2.5.1"},
            {"id": 17, "question": "Aircraft speed at exit is determined by whom for AE?", "options": ["Chief Judge", "Meet Director", "Chief Pilot", "Team"], "correct": 1, "correct_section": "2.1.1"},
            {"id": 18, "question": "The minimum number of rounds to constitute a meet is one (the free round).", "options": ["True", "False", "Two rounds minimum", "Three rounds minimum"], "correct": 0, "correct_section": "3.3.1"},
            {"id": 19, "question": "Working time starts when for Artistic Events?", "options": ["Any team member separates from aircraft", "Videographer exit", "First performer exit", "First formation"], "correct": 0, "correct_section": "1.1.7"},
            {"id": 20, "question": "If judges cannot determine start of working time, what is used?", "options": ["Rejump granted", "Videographer separates from aircraft", "Average time applied", "Zero score"], "correct": 1, "correct_section": "4.4.6"},
            {"id": 21, "question": "A penalty of what percent is deducted if start time cannot be determined?", "options": ["10%", "15%", "20%", "25%"], "correct": 2, "correct_section": "4.4.6"},
            {"id": 22, "question": "A Freestyle team has how many performers (not including videographer)?", "options": ["One", "Two", "Three", "Four"], "correct": 0, "correct_section": "1.1.1"},
            {"id": 23, "question": "A Freefly team has how many performers (not including videographer)?", "options": ["One", "Two", "Three", "Four"], "correct": 1, "correct_section": "1.1.2"},
            {"id": 24, "question": "Each Compulsory Routine consists of how many Compulsory Sequences?", "options": ["Two", "Three", "Four", "Five"], "correct": 2, "correct_section": "3.2.2"},
            {"id": 25, "question": "For ties in the first three places, what is the first tie-breaking method?", "options": ["Tie-break free round", "Sum of free rounds", "Highest single round", "Co-placing"], "correct": 0, "correct_section": "5.3.1"},
        ]
    },
    "ch11_national": {
        "name": "Chapter 11: Artistic Events - National Test",
        "chapter": "AE",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "If tie persists after comparing free rounds, what is compared next?", "options": ["Compulsory rounds", "Last free round", "Highest single round", "Average score"], "correct": 0, "correct_section": "5.3.2.2"},
            {"id": 2, "question": "The first three places in a tie are determined by a tie-break free round if what?", "options": ["Chief Judge decides", "Time permits", "Teams agree", "Always required"], "correct": 1, "correct_section": "5.3.1"},
            {"id": 3, "question": "Teams must deliver compulsory sequence order and Max Values when?", "options": ["Day of competition", "Before competition begins", "After first round", "48 hours before"], "correct": 1, "correct_section": "3.2.4.1"},
            {"id": 4, "question": "Failure to provide compulsory sequence order results in what score?", "options": ["Average score", "Zero points", "Penalty deduction", "Rejump offered"], "correct": 1, "correct_section": "3.2.4.2"},
            {"id": 5, "question": "Free routine videos must be delivered to Chief Judge how long before registration closes?", "options": ["24 hours", "48 hours", "72 hours", "1 week"], "correct": 1, "correct_section": "3.2.4.3"},
            {"id": 6, "question": "Each Compulsory Routine consists of how many Compulsory Sequences?", "options": ["Two", "Three", "Four", "Five"], "correct": 2, "correct_section": "3.2.2"},
            {"id": 7, "question": "Compulsory Sequences must be performed in what order?", "options": ["Any order", "Submitted order", "Numerical order", "Difficulty order"], "correct": 1, "correct_section": "3.2.2"},
            {"id": 8, "question": "In free rounds, execution deductions are determined by how many judges?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "4.2.2.1"},
            {"id": 9, "question": "The compulsory sequence average is multiplied by what factor?", "options": ["0.1", "0.225", "0.5", "1.0"], "correct": 1, "correct_section": "4.5.2.2"},
            {"id": 10, "question": "The presentation average in compulsory rounds is multiplied by what factor?", "options": ["0.1", "0.225", "0.5", "1.0"], "correct": 0, "correct_section": "4.5.2.2"},
            {"id": 11, "question": "All three judges' scores are averaged with no rounding applied.", "options": ["True", "False", "Only for free", "Only for compulsory"], "correct": 0, "correct_section": "4.5.2.1"},
            {"id": 12, "question": "Executing compulsory sequences in wrong order results in what for out-of-order sequences?", "options": ["Penalty points", "Zero score", "Rejump", "Warning"], "correct": 1, "correct_section": "4.3.3.1"},
            {"id": 13, "question": "If judges recognize an attempt at a compulsory sequence, a second attempt receives what?", "options": ["Full score", "Half score", "No score", "Bonus points"], "correct": 2, "correct_section": "4.3.3"},
            {"id": 14, "question": "Working time terminates how many seconds after exit for Freestyle?", "options": ["40 seconds", "43 seconds", "45 seconds", "50 seconds"], "correct": 2, "correct_section": "1.1.7.1"},
            {"id": 15, "question": "Freestyle Team Members are allowed to change their position in the team.", "options": ["True", "False", "Only once", "Only with approval"], "correct": 0, "correct_section": "3.1.3"},
            {"id": 16, "question": "Only one Team Member may carry freefall video equipment on any particular round.", "options": ["True", "False", "Two allowed", "Unlimited"], "correct": 0, "correct_section": "3.1.3"},
            {"id": 17, "question": "Presentation in compulsory routines is scored for what?", "options": ["Whole routine", "Beginning, end, and moves between sequences", "Sequences only", "Exit only"], "correct": 1, "correct_section": "4.3.2"},
            {"id": 18, "question": "Camera deductions in free rounds can be up to what for performer too far from camera?", "options": ["-1.0 points", "-2.0 points", "-3.0 points", "-5.0 points"], "correct": 1, "correct_section": "4.2.3.2"},
            {"id": 19, "question": "A performer and videographer may be on at most how many Freestyle teams?", "options": ["One", "Two", "Three", "Unlimited"], "correct": 0, "correct_section": "3.1.5"},
            {"id": 20, "question": "Judges watch each jump how many times with an optional second viewing?", "options": ["Once", "Twice", "Three times", "Unlimited"], "correct": 0, "correct_section": "4.4.3"},
            {"id": 21, "question": "A third view of a compulsory round jump is allowed at whose discretion?", "options": ["Team request", "Chief Judge", "Majority of judges", "Event Judge"], "correct": 3, "correct_section": "4.4.3"},
            {"id": 22, "question": "Problems with a team's equipment are grounds for a rejump.", "options": ["True", "False", "Only video equipment", "Only safety equipment"], "correct": 1, "correct_section": "2.4.3"},
            {"id": 23, "question": "Contact between performers and videographer is grounds for a rejump.", "options": ["True", "False", "Only if intentional", "Chief Judge decides"], "correct": 1, "correct_section": "2.4.2"},
            {"id": 24, "question": "Adverse weather during a jump is grounds for protest.", "options": ["True", "False", "Only for rejump", "Chief Judge decides"], "correct": 1, "correct_section": "2.4.4"},
            {"id": 25, "question": "A Freefly team consists of how many Team Members total?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "3.1.4"},
        ]
    },
    "ch12_13_regional": {
        "name": "Chapters 12 & 13: Canopy Piloting - Regional Test",
        "chapter": "CP",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "What is the minimum exit altitude for CP with 1-2 competitors?", "options": ["1000 meters AGL", "1200 meters AGL", "1500 meters AGL", "2000 meters AGL"], "correct": 1, "correct_section": "3.2.1"},
            {"id": 2, "question": "How many events comprise Canopy Piloting?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "1.2.1"},
            {"id": 3, "question": "What are the three CP events?", "options": ["Speed, Distance, Style", "Speed, Distance, Zone Accuracy", "Speed, Accuracy, Style", "Distance, Accuracy, Freestyle"], "correct": 1, "correct_section": "2.1"},
            {"id": 4, "question": "What is the course length for Carved Speed?", "options": ["50 meters", "60 meters", "70 meters", "80 meters"], "correct": 2, "correct_section": "Addendum C 1.1.1"},
            {"id": 5, "question": "What is the maximum ground wind speed for CP Speed and Distance events?", "options": ["5 m/s", "7 m/s", "9 m/s", "11 m/s"], "correct": 1, "correct_section": "3.1.1"},
            {"id": 6, "question": "Each CP performance shall be observed by at least how many judges?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "5.1.3"},
            {"id": 7, "question": "In Zone Accuracy, the top ranked competitor's score is set to what percentage?", "options": ["50%", "75%", "100%", "125%"], "correct": 2, "correct_section": "4.5.2"},
            {"id": 8, "question": "In Distance, scoring begins at what point?", "options": ["Exit point", "Entry gate (G1)", "Water contact", "Course start"], "correct": 1, "correct_section": "4.3.5.2"},
            {"id": 9, "question": "What is the width of the CP course?", "options": ["10 meters", "12 meters", "15 meters", "20 meters"], "correct": 0, "correct_section": "Addendum B 1.1.2"},
            {"id": 10, "question": "How many rounds are scheduled per CP event (Speed, Distance, Zone Accuracy)?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "1.2.1"},
            {"id": 11, "question": "The minimum number of rounds for a valid CP event is one.", "options": ["True", "False", "Two rounds required", "Three rounds required"], "correct": 0, "correct_section": "1.2.3"},
            {"id": 12, "question": "What result applies for a Missed Entry (ME) in CP?", "options": ["Default result", "Minimum result (zero points)", "Rejump offered", "Average of other rounds"], "correct": 1, "correct_section": "4.1.4.1"},
            {"id": 13, "question": "The Overall Champion is the competitor with the highest what?", "options": ["Total points from all events", "Average placing", "Combined event scores", "Best three rounds"], "correct": 0, "correct_section": "7.1.2"},
            {"id": 14, "question": "What is the Default Result (DR) in CP events?", "options": ["Zero points", "Three points", "Five points", "Ten points"], "correct": 1, "correct_section": "Addendum A"},
            {"id": 15, "question": "CP-Freestyle is covered in which chapter?", "options": ["Chapter 12", "Chapter 13", "Chapter 14", "Appendix"], "correct": 1, "correct_section": "13-1.1.1"},
            {"id": 16, "question": "What is the minimum exit altitude for CP-Freestyle with 1-2 competitors?", "options": ["1000 meters AGL", "1200 meters AGL", "1500 meters AGL", "2000 meters AGL"], "correct": 1, "correct_section": "3.2.1"},
            {"id": 17, "question": "How many rounds comprise a CP-Freestyle competition?", "options": ["One", "Two", "Three", "Four"], "correct": 2, "correct_section": "1.2.1"},
            {"id": 18, "question": "What is the minimum number of rounds required for a valid CP-Freestyle event?", "options": ["One", "Two", "Three", "Four"], "correct": 0, "correct_section": "1.2.2"},
            {"id": 19, "question": "CP-Freestyle is an individual event.", "options": ["True", "False", "Team of two", "Team of three"], "correct": 0, "correct_section": "2.1.1"},
            {"id": 20, "question": "Each judge scores CP-Freestyle performances from 0.0 to what maximum?", "options": ["5.0", "7.5", "10.0", "15.0"], "correct": 2, "correct_section": "4.1.7"},
            {"id": 21, "question": "How many judges evaluate each CP-Freestyle jump?", "options": ["Three", "Four", "Five", "Six"], "correct": 2, "correct_section": "4.1.7"},
            {"id": 22, "question": "In Speed, the course ends at what?", "options": ["Water exit", "Exit gate", "100-meter mark", "Landing"], "correct": 1, "correct_section": "12-4.2.1"},
            {"id": 23, "question": "What is the Default Result (DR) in CP-Freestyle?", "options": ["Zero points", "Three points", "Five points", "Ten points"], "correct": 1, "correct_section": "2.2"},
            {"id": 24, "question": "The maximum wind speed for CP-Freestyle is what?", "options": ["5 m/s", "7 m/s", "9 m/s", "11 m/s"], "correct": 1, "correct_section": "3.1.1"},
            {"id": 25, "question": "What is the maximum points possible in CP-Freestyle (3 rounds)?", "options": ["100 points", "200 points", "300 points", "400 points"], "correct": 2, "correct_section": "7.1.1"},
        ]
    },
    "ch12_13_national": {
        "name": "Chapters 12 & 13: Canopy Piloting - National Test",
        "chapter": "CP",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "In Speed, time is measured to what precision?", "options": ["0.1 seconds", "0.01 seconds", "0.001 seconds", "0.0001 seconds"], "correct": 2, "correct_section": "4.2.3"},
            {"id": 2, "question": "In Distance, measurements are to what precision?", "options": ["0.1 meters", "0.5 meters", "1 meter", "0.01 meters"], "correct": 3, "correct_section": "4.3.5.2"},
            {"id": 3, "question": "A video review (VR) cycle is comprised of a maximum of how many viewings?", "options": ["One", "Two", "Three", "Four"], "correct": 2, "correct_section": "12-6.2.4"},
            {"id": 4, "question": "If Out Flying (OF) occurs after G1 is scored, what result is issued?", "options": ["Minimum result (0 points)", "Default result (3 points)", "Rejump offered", "Disqualification"], "correct": 1, "correct_section": "4.1.3"},
            {"id": 5, "question": "In Distance, what is measured from G1 to determine score?", "options": ["Distance to water exit", "Distance to G5", "Distance to closest point touched during landing", "Distance to landing stop"], "correct": 2, "correct_section": "4.3.5.2"},
            {"id": 6, "question": "How many zones comprise Zone Accuracy in CP?", "options": ["Six", "Eight", "Ten", "Twelve"], "correct": 2, "correct_section": "12-Addendum E"},
            {"id": 7, "question": "In CP tied placing for first three places, what is the first tiebreaker?", "options": ["One tie-breaking jump", "Best single round result", "Overall points", "Speed result"], "correct": 0, "correct_section": "7.2.1.1"},
            {"id": 8, "question": "The host must provide how many additional persons to assist CP-Freestyle judges?", "options": ["One", "Two", "Three", "Four"], "correct": 1, "correct_section": "13-5.1.3.1"},
            {"id": 9, "question": "At least one CP-Freestyle helper must be able to operate what?", "options": ["Timing system", "Video judging system", "Wind meter", "Radio"], "correct": 1, "correct_section": "13-5.1.3.1"},
            {"id": 10, "question": "CP-Freestyle helpers should preferably have what rating?", "options": ["Regional FS judge", "National CP judge", "Local CP judge", "Any judge rating"], "correct": 2, "correct_section": "13-5.1.3.1"},
            {"id": 11, "question": "CP-Freestyle helpers must be approved by whom no later than day before OPP?", "options": ["Meet Director", "Chief Judge", "Video Controller", "USPA Controller"], "correct": 1, "correct_section": "13-5.1.3.1"},
            {"id": 12, "question": "What is the maximum allowable wind speed for Zone Accuracy in CP?", "options": ["5 m/s", "6 m/s", "7 m/s", "9 m/s"], "correct": 0, "correct_section": "12-3.1.1"},
            {"id": 13, "question": "What is the fee to invoke a video review challenge in CP?", "options": ["$25", "$50", "$75", "$100"], "correct": 2, "correct_section": "12-6.3.5"},
            {"id": 14, "question": "In CP-Freestyle Open class Round 1, moves must have DoD less than what?", "options": ["2.0", "3.0", "4.0", "5.0"], "correct": 3, "correct_section": "4.1.1.1"},
            {"id": 15, "question": "In CP-Freestyle Intermediate class Round 1, moves must have DoD less than what?", "options": ["2.0", "3.0", "4.0", "5.0"], "correct": 0, "correct_section": "4.1.2.1"},
            {"id": 16, "question": "Routine description sheets must be presented how long before competition start?", "options": ["24 hours", "36 hours", "48 hours", "72 hours"], "correct": 2, "correct_section": "4.1.3"},
            {"id": 17, "question": "If routine description sheet is not presented on time, the DoD for each round will be what?", "options": ["1.0", "1.2", "1.5", "2.0"], "correct": 1, "correct_section": "4.1.3"},
            {"id": 18, "question": "A penalty in CP-Freestyle is applied when indicated by a minimum of how many judges?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "4.1.8"},
            {"id": 19, "question": "In CP-Freestyle tied placing, what determines higher standing first?", "options": ["Best single score", "Higher placing in completed rounds", "Last round score", "Total points"], "correct": 1, "correct_section": "7.2.1"},
            {"id": 20, "question": "In CP, competitors jump in what order in later rounds?", "options": ["Random", "Registration order", "Reverse standings", "Same order"], "correct": 2, "correct_section": "12-3.5.5"},
            {"id": 21, "question": "The CP water course minimum depth at the beginning to G2 is what?", "options": ["0.40 meters", "0.50 meters", "0.60 meters", "0.75 meters"], "correct": 2, "correct_section": "Addendum B 1.1.4.1"},
            {"id": 22, "question": "In Speed, what triggers the timing system start?", "options": ["Exit signal", "Entry gate", "First water contact", "Competitor signal"], "correct": 1, "correct_section": "12-4.2.1"},
            {"id": 23, "question": "The video review panel in CP-Freestyle consists of how many persons?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "6.2.2"},
            {"id": 24, "question": "One complete round constitutes a meet for CP-Freestyle.", "options": ["True", "False", "Two rounds", "Three rounds"], "correct": 0, "correct_section": "1.2.2"},
            {"id": 25, "question": "What is the minimum number of high-performance landings for CP Open class?", "options": ["100 in 12 months", "150 in 12 months", "200 total", "500 total"], "correct": 1, "correct_section": "1-5.2.2"},
        ]
    },
    "ch14_regional": {
        "name": "Chapter 14: Wingsuit Flying - Regional Test",
        "chapter": "WS",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "What is the maximum exit altitude for Wingsuit Performance?", "options": ["10,000 feet", "10,500 feet", "11,000 feet", "12,500 feet"], "correct": 2, "correct_section": "5.4.6"},
            {"id": 2, "question": "What is the minimum exit altitude for Wingsuit Acrobatic?", "options": ["10,000 feet", "11,000 feet", "12,000 feet", "12,500 feet"], "correct": 2, "correct_section": "6.3.1"},
            {"id": 3, "question": "How many tasks comprise Wingsuit Performance?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "5.1.1"},
            {"id": 4, "question": "What are the three Performance tasks?", "options": ["Time, Distance, Speed", "Speed, Distance, Time", "Distance, Speed, Altitude", "Time, Distance, Style"], "correct": 0, "correct_section": "5.3"},
            {"id": 5, "question": "Wingsuit Performance is an individual event.", "options": ["True", "False", "Team of two", "Team of three"], "correct": 0, "correct_section": "5.1.1"},
            {"id": 6, "question": "Wingsuit Acrobatic team size is how many including videographer?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "2.3.1"},
            {"id": 7, "question": "How many compulsory rounds in WS Acrobatic?", "options": ["Two", "Three", "Four", "Five"], "correct": 2, "correct_section": "6.2.2.1"},
            {"id": 8, "question": "How many free rounds in WS Acrobatic?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "6.2.2.2"},
            {"id": 9, "question": "The Acrobatic Altitude Window lower boundary is how many feet below the upper boundary?", "options": ["5,000 feet", "6,500 feet", "7,500 feet", "8,000 feet"], "correct": 2, "correct_section": "6.3.3"},
            {"id": 10, "question": "How many judges minimum for Wingsuit Performance?", "options": ["Two", "Three", "Four", "Five"], "correct": 0, "correct_section": "7.1.2"},
            {"id": 11, "question": "How many judges minimum for Wingsuit Acrobatic?", "options": ["Three", "Four", "Five", "Six"], "correct": 0, "correct_section": "7.2.3"},
            {"id": 12, "question": "What is the maximum wind speed for Wingsuit events?", "options": ["7 m/s", "9 m/s", "11 m/s", "13 m/s"], "correct": 1, "correct_section": "5.7.4"},
            {"id": 13, "question": "The Performance competition window is between what altitudes?", "options": ["2500m-1500m (8202-4921 ft)", "3000m-2000m", "2000m-1000m", "3500m-2500m"], "correct": 0, "correct_section": "2.2.1"},
            {"id": 14, "question": "How many rounds does a WS Performance competition consist of?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "5.4.1"},
            {"id": 15, "question": "How many rounds does a WS Acrobatic competition consist of?", "options": ["Six", "Seven", "Eight", "Ten"], "correct": 1, "correct_section": "6.2.1"},
            {"id": 16, "question": "A valid WS Performance competition requires at least one valid task.", "options": ["True", "False", "One round", "Three tasks"], "correct": 0, "correct_section": "5.4.4"},
            {"id": 17, "question": "What is the minimum horizontal spacing between exits in WS Performance?", "options": ["400m", "500m", "600m", "800m"], "correct": 2, "correct_section": "5.5.5"},
            {"id": 18, "question": "In WS Performance, scores are recorded using what?", "options": ["Video", "Ground observers", "Position Logging Device (PLD)", "Timing gates"], "correct": 2, "correct_section": "2.1.2"},
            {"id": 19, "question": "The Speed task measures what?", "options": ["Horizontal ground speed (km/h)", "Vertical speed", "Air speed", "Total velocity"], "correct": 0, "correct_section": "5.3.3"},
            {"id": 20, "question": "The Time task measures what?", "options": ["Total flight time", "Time in competition window (seconds)", "Time to target", "Freefall time"], "correct": 1, "correct_section": "5.3.1"},
            {"id": 21, "question": "The Distance task measures what?", "options": ["Total distance", "Straight-line ground distance (meters)", "Vertical distance", "3D distance"], "correct": 1, "correct_section": "5.3.2"},
            {"id": 22, "question": "WS Acrobatic performers (not including videographer) must be how many?", "options": ["One", "Two", "Three", "Four"], "correct": 1, "correct_section": "2.3.1"},
            {"id": 23, "question": "With 5 judges in WS Acrobatic, the highest and lowest scores are discarded.", "options": ["True", "False", "Only compulsory", "Only free"], "correct": 0, "correct_section": "7.2.8.1"},
            {"id": 24, "question": "WS Performance Overall uses what calculation method?", "options": ["Total points", "Average placing", "Sum of percentage scores", "Best rounds"], "correct": 2, "correct_section": "5.9.3"},
            {"id": 25, "question": "A wingsuit is defined as a garment forming wings between what?", "options": ["Arms only", "Legs only", "Arms, legs, and torso", "Inflatable cells"], "correct": 2, "correct_section": "2.1.1"},
        ]
    },
    "ch14_national": {
        "name": "Chapter 14: Wingsuit Flying - National Test",
        "chapter": "WS",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "In WS Performance, what happens if PLD malfunctions (not competitor's fault)?", "options": ["Rejump option offered", "Zero score", "Average of other rounds", "DNF"], "correct": 0, "correct_section": "4.2.11"},
            {"id": 2, "question": "The Performance competition window upper boundary is at what Geometric Altitude?", "options": ["2000m", "2500m (8202ft)", "3000m", "3500m"], "correct": 1, "correct_section": "2.2.1"},
            {"id": 3, "question": "The Performance competition window lower boundary is at what Geometric Altitude?", "options": ["1000m", "1500m (4921ft)", "2000m", "2500m"], "correct": 1, "correct_section": "2.2.1"},
            {"id": 4, "question": "For Performance, the Meet Director may lower exit altitude to no lower than what?", "options": ["9,000 feet", "10,000 feet (3048m)", "11,000 feet", "11,500 feet"], "correct": 1, "correct_section": "5.4.7"},
            {"id": 5, "question": "If Performance exit altitude is lowered, what happens to the competition window?", "options": ["Lowered proportionally", "Lowered 1,500 feet", "Lowered 2,000 feet", "Window stays 2500-1500m"], "correct": 3, "correct_section": "5.4.7"},
            {"id": 6, "question": "WS Acrobatic compulsory sequences contain how many maneuvers?", "options": ["2 or 4", "3 only", "4 only", "5"], "correct": 0, "correct_section": "2.3.5"},
            {"id": 7, "question": "In WS Acrobatic compulsory rounds, style is scored on a scale of what?", "options": ["0-5 points", "0-10 points", "0-15 points", "0-20 points"], "correct": 1, "correct_section": "Addendum B C-2"},
            {"id": 8, "question": "WS Acrobatic compulsory rounds are evaluated using what criteria?", "options": ["Style only", "Style and number of grips", "Grips only", "Style, grips, and camera"], "correct": 1, "correct_section": "7.2.6.1"},
            {"id": 9, "question": "WS Acrobatic free rounds are evaluated using what criteria?", "options": ["Style only", "Style and grips", "Style, dive plan, and camerawork", "Dive plan only"], "correct": 2, "correct_section": "7.2.7.1"},
            {"id": 10, "question": "Camera Quality in free rounds is scored on a scale of what?", "options": ["0-5 points", "0-7 points", "0-10 points", "0-15 points"], "correct": 1, "correct_section": "Addendum B C-3"},
            {"id": 11, "question": "Progressive Work in free rounds is scored on a scale of what?", "options": ["0-3 points", "0-5 points", "0-7 points", "0-10 points"], "correct": 0, "correct_section": "Addendum B C-3"},
            {"id": 12, "question": "Working time starts when for WS Acrobatic?", "options": ["Any team member exits", "Last exit", "Videographer exit", "Vertical speed reaches 10 m/s"], "correct": 0, "correct_section": "2.4.10"},
            {"id": 13, "question": "A penalty of what percent is deducted if start of working time cannot be determined on video?", "options": ["10%", "15%", "20%", "25%"], "correct": 0, "correct_section": "6.8.8"},
            {"id": 14, "question": "In WS Performance tied placing (first three places), what happens?", "options": ["Best single round compared", "Sum of task scores", "Tie-break jump made", "Speed score"], "correct": 2, "correct_section": "5.9.5.1"},
            {"id": 15, "question": "In WS Acrobatic tie after tie-break jump, what is compared first?", "options": ["Best compulsory rounds", "Best score of free rounds", "Average of all rounds", "Last round"], "correct": 1, "correct_section": "6.10.3.1"},
            {"id": 16, "question": "How many compulsory sequences make up a compulsory routine?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "6.6.1"},
            {"id": 17, "question": "An Acrobatic Wingsuit Flying Team consists of exactly how many members?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "2.3.1"},
            {"id": 18, "question": "Speed task result in WS Performance is expressed in what units?", "options": ["mph", "knots", "km/h", "m/s"], "correct": 2, "correct_section": "5.3.3"},
            {"id": 19, "question": "Time task result in WS Performance is expressed in what units?", "options": ["Milliseconds", "Centiseconds", "Seconds", "Minutes"], "correct": 2, "correct_section": "5.3.1"},
            {"id": 20, "question": "Distance task result in WS Performance is expressed in what units?", "options": ["Feet", "Meters", "Kilometers", "Miles"], "correct": 1, "correct_section": "5.3.2"},
            {"id": 21, "question": "The PLD must have a position accuracy (SEP) of less than how many meters?", "options": ["5 meters", "10 meters", "15 meters", "20 meters"], "correct": 1, "correct_section": "4.1.1"},
            {"id": 22, "question": "Each competitor shall wear how many PLD(s) provided by the Host?", "options": ["One", "Two", "Three", "One primary, one backup"], "correct": 0, "correct_section": "5.8.4"},
            {"id": 23, "question": "The PLD must record data with a resolution of at least what frequency?", "options": ["1Hz", "5Hz", "10Hz", "20Hz"], "correct": 1, "correct_section": "4.1.1"},
            {"id": 24, "question": "If the PLD is lost, what score does the competitor receive?", "options": ["Zero", "Average of others", "Rejump", "DNF"], "correct": 0, "correct_section": "4.2.12"},
            {"id": 25, "question": "WS Performance scores are calculated as what of the top result?", "options": ["Raw scores", "Percentage of top result", "Standard deviations", "Rankings only"], "correct": 1, "correct_section": "5.9.2"},
        ]
    },
    "ch15_regional": {
        "name": "Chapter 15: Speed Skydiving - Regional Test",
        "chapter": "SP",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "What is the standard minimum exit altitude for Speed Skydiving?", "options": ["12,000 feet", "13,000 feet", "14,000 feet", "15,000 feet"], "correct": 1, "correct_section": "5.4.1"},
            {"id": 2, "question": "Speed Skydiving is an individual event.", "options": ["True", "False", "Team of two", "Team of three"], "correct": 0, "correct_section": "4.2.1"},
            {"id": 3, "question": "How many rounds does the Speed Skydiving Individual Event consist of?", "options": ["Six", "Eight", "Ten", "Twelve"], "correct": 1, "correct_section": "4.2.1"},
            {"id": 4, "question": "The performance window ends at what altitude (breakoff)?", "options": ["4,500 ft AGL", "5,000 ft AGL", "5,600 ft AGL", "6,000 ft AGL"], "correct": 2, "correct_section": "2.6.1"},
            {"id": 5, "question": "What is measured in Speed Skydiving?", "options": ["Ground speed", "Horizontal speed", "Vertical speed", "Total velocity"], "correct": 2, "correct_section": "4.1.1"},
            {"id": 6, "question": "Speed is measured using what devices?", "options": ["Video analysis", "Radar", "Position Logging Device (PLD)", "Timing gates"], "correct": 2, "correct_section": "2.1.1"},
            {"id": 7, "question": "How many judges minimum for Speed Skydiving?", "options": ["Two", "Three", "Four", "Five"], "correct": 0, "correct_section": "6.1.1"},
            {"id": 8, "question": "The score is the average vertical speed over how many seconds?", "options": ["2 seconds", "3 seconds", "4 seconds", "5 seconds"], "correct": 1, "correct_section": "4.1.1"},
            {"id": 9, "question": "The minimum number of rounds for a valid Speed Skydiving event is how many?", "options": ["One", "Two", "Three", "Four"], "correct": 0, "correct_section": "4.2.1"},
            {"id": 10, "question": "The exit delay between competitors must be at least how many seconds?", "options": ["3 seconds", "5 seconds", "7 seconds", "10 seconds"], "correct": 1, "correct_section": "5.2.2"},
            {"id": 11, "question": "Speed is recorded in what units?", "options": ["mph", "knots", "km/h", "m/s"], "correct": 2, "correct_section": "5.5.1"},
            {"id": 12, "question": "Speed Skydiving competitors are ranked by what?", "options": ["Total speed", "Average speed", "Best single round", "Accumulation/sum of scores"], "correct": 3, "correct_section": "6.3.1"},
            {"id": 13, "question": "The performance window height is how many feet below the start?", "options": ["5,000 feet", "6,000 feet", "7,400 feet", "8,000 feet"], "correct": 2, "correct_section": "2.7.1"},
            {"id": 14, "question": "The PLD is attached to the competitor's helmet by whom?", "options": ["Competitor", "Team captain", "Judging staff member", "Meet Director"], "correct": 2, "correct_section": "3.2.6"},
            {"id": 15, "question": "If PLD malfunctions (not competitor's fault), what options does competitor have?", "options": ["Zero score only", "Rejump or zero score", "Automatic rejump", "Average of other rounds"], "correct": 1, "correct_section": "3.2.14"},
            {"id": 16, "question": "If PLD is tampered with by competitor, what is the result?", "options": ["Warning", "Rejump", "Zero score for jump", "Disqualification"], "correct": 2, "correct_section": "3.2.13"},
            {"id": 17, "question": "In tied placing (first three places), what is tried first?", "options": ["Best single round", "Tie-break jump", "Total speed", "Co-medalists declared"], "correct": 1, "correct_section": "7.1.2.1"},
            {"id": 18, "question": "The PLD must record data with a resolution of at least what frequency?", "options": ["1Hz", "3Hz", "5Hz", "10Hz"], "correct": 2, "correct_section": "3.1.1"},
            {"id": 19, "question": "The performance window starts when vertical speed first reaches what?", "options": ["5 m/s", "10 m/s", "15 m/s", "20 m/s"], "correct": 1, "correct_section": "2.7.1"},
            {"id": 20, "question": "Scores of all completed rounds are accumulated for final standings.", "options": ["True", "False", "Drop lowest", "Best 6 of 8"], "correct": 0, "correct_section": "6.3.1"},
            {"id": 21, "question": "The breakoff altitude in meters is approximately what?", "options": ["1,500 m", "1,707 m", "1,900 m", "2,000 m"], "correct": 1, "correct_section": "2.6.1"},
            {"id": 22, "question": "The performance window height in meters is approximately what?", "options": ["1,500 m", "2,000 m", "2,256 m", "2,500 m"], "correct": 2, "correct_section": "2.7.1"},
            {"id": 23, "question": "Mixed teams compete for separate medals.", "options": ["True", "False", "Only at Nationals", "Only at Worlds"], "correct": 0, "correct_section": "7.1.3.2"},
            {"id": 24, "question": "How many competitors form a mixed team?", "options": ["Two", "Three", "Four", "Five"], "correct": 0, "correct_section": "4.2.2"},
            {"id": 25, "question": "A mixed team includes how many male and how many female competitors?", "options": ["One male, one female", "Two male, one female", "One male, two female", "Any combination"], "correct": 0, "correct_section": "4.2.2"},
        ]
    },
    "general": {
        "name": "Chapters 1-3: General Competition Rules",
        "chapter": "GR",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "What is the minimum number of freefall skydives required to compete at a USPA National Skydiving Championships?", "options": ["50 skydives", "75 skydives", "100 skydives", "200 skydives"], "correct": 2, "correct_section": "1-5.2.1"},
            {"id": 2, "question": "What is the minimum age requirement to compete at USPA Nationals?", "options": ["16 years", "17 years", "18 years", "21 years"], "correct": 2, "correct_section": "1-5.2.1"},
            {"id": 3, "question": "What is the maximum wind limit for all events unless otherwise specified?", "options": ["7 m/s", "9 m/s", "11 m/s", "13 m/s"], "correct": 2, "correct_section": "1-8.3.2"},
            {"id": 4, "question": "How long do competitors have to file a protest after knowledge of the grounds for protest?", "options": ["30 minutes", "1 hour", "2 hours", "24 hours"], "correct": 2, "correct_section": "1-8.4.2"},
            {"id": 5, "question": "What fee must accompany a protest?", "options": ["$25", "$50", "$75", "$100"], "correct": 1, "correct_section": "1-8.4.4"},
            {"id": 6, "question": "What is the minimum license required for Formation Skydiving Open class?", "options": ["A License", "B License", "C License", "D License"], "correct": 2, "correct_section": "1-Table 1"},
            {"id": 7, "question": "The Meet Director may NOT be a competitor in any event.", "options": ["True", "False", "Only in team events", "Only with Jury approval"], "correct": 0, "correct_section": "1-4.1.4"},
            {"id": 8, "question": "How many aircraft passes over the target are permitted per competitor or team for any jump?", "options": ["One", "Two", "Three", "Unlimited"], "correct": 1, "correct_section": "1-8.2.3.1"},
            {"id": 9, "question": "What is the minimum advance call time before boarding the aircraft?", "options": ["5 minutes only", "10 and 5 minutes", "15 and 5 minutes", "20 and 10 minutes"], "correct": 2, "correct_section": "1-7.5.1"},
            {"id": 10, "question": "For Open class Canopy Piloting, how many high-performance landings are required in the last 12 months?", "options": ["100 landings", "125 landings", "150 landings", "200 landings"], "correct": 2, "correct_section": "1-5.2.2"},
            {"id": 11, "question": "The panel of judges for a discipline must comprise an event judge plus at least how many other judges?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "correct_section": "1-4.2.4"},
            {"id": 12, "question": "What is the penalty for failure to meet video requirements at a USPA Nationals?", "options": ["Zero score", "10% score penalty", "20% score penalty", "Rejump required"], "correct": 2, "correct_section": "1-7.3.1"},
            {"id": 13, "question": "What is the minimum score required on the written exam for a Regional Judge rating?", "options": ["70%", "75%", "80%", "85%"], "correct": 1, "correct_section": "2-6.5.2"},
            {"id": 14, "question": "What is the minimum score required on the practical exam for a National Judge rating?", "options": ["75%", "80%", "85%", "90%"], "correct": 2, "correct_section": "2-6.5.3"},
            {"id": 15, "question": "How long is a USPA member required to have been a member before earning a National Judge rating?", "options": ["6 months", "1 year", "2 years", "3 years"], "correct": 1, "correct_section": "2-3.2.1"},
            {"id": 16, "question": "What is the initial judge rating fee that includes a logbook?", "options": ["$25", "$35", "$45", "$50"], "correct": 1, "correct_section": "2-3.5.1.2"},
            {"id": 17, "question": "A National Judge rating automatically expires at the end of which calendar year?", "options": ["Third year", "Fourth year", "Fifth year", "Seventh year"], "correct": 2, "correct_section": "2-5.1.2.1"},
            {"id": 18, "question": "By what date must judges contact the Director of Competition to be on the active judges list?", "options": ["October 1", "November 1", "December 1", "January 1"], "correct": 2, "correct_section": "2-5.2.1"},
            {"id": 19, "question": "To apply for Judge Examiner appointment, how many consecutive years must a judge be on the active list?", "options": ["Three years", "Four years", "Five years", "Seven years"], "correct": 2, "correct_section": "2-6.3.1"},
            {"id": 20, "question": "A Regional Judge's rating is valid for how long?", "options": ["1 year", "3 years", "5 years", "Permanent with USPA membership"], "correct": 3, "correct_section": "2-5.1.1.1"},
            {"id": 21, "question": "Who has authority to impose regulations due to unforeseeable exigencies during competition?", "options": ["Chief Judge only", "Meet Director only", "Meet Management", "The Jury"], "correct": 2, "correct_section": "1-6.3.1"},
            {"id": 22, "question": "What is the minimum number of judges required for Accuracy Landing?", "options": ["Three judges", "Four judges", "Five judges", "Six judges"], "correct": 2, "correct_section": "1-4.2.6"},
            {"id": 23, "question": "How many years can the same person serve as Chief Judge in the same discipline consecutively?", "options": ["One year", "Two years", "Three years", "No limit"], "correct": 1, "correct_section": "2-7.3.1.1"},
            {"id": 24, "question": "What minimum score on absolute assessments is required for FS and CF judge training?", "options": ["70%", "75%", "80%", "85%"], "correct": 2, "correct_section": "2-6.6.1"},
            {"id": 25, "question": "What organization delegated USPA authority over skydiving competition in the United States?", "options": ["FAA", "FAI", "NAA", "ISC"], "correct": 2, "correct_section": "1-1.3.1"},
        ]
    },
    "ch15_national": {
        "name": "Chapter 15: Speed Skydiving - National Test",
        "chapter": "SP",
        "passing_score": 75,
        "questions": [
            {"id": 1, "question": "For weather/ATC reasons, the minimum exit altitude may be reduced to what?", "options": ["10,000 feet", "11,000 feet", "12,000 feet", "12,500 feet"], "correct": 1, "correct_section": "5.4.2"},
            {"id": 2, "question": "When exit altitude is reduced, how is the performance window adjusted?", "options": ["Stays the same", "Reduced by same amount", "Always uses full window", "Breakoff changes"], "correct": 1, "correct_section": "5.4.2"},
            {"id": 3, "question": "Any one round must be completed with what altitude parameters?", "options": ["Any altitude OK", "The same parameters", "Full altitude only", "Varied as needed"], "correct": 1, "correct_section": "5.4.2"},
            {"id": 4, "question": "The maximum exit altitude for a valid jump is what?", "options": ["13,000 feet", "14,000 feet", "15,000 feet", "16,000 feet"], "correct": 1, "correct_section": "5.4.3"},
            {"id": 5, "question": "If exit altitude exceeds the maximum, what happens?", "options": ["Score stands", "Rejump granted", "Zero score", "Warning issued"], "correct": 1, "correct_section": "5.4.3"},
            {"id": 6, "question": "If exit altitude is below minimum, competitor may choose to?", "options": ["Automatic rejump", "Accept score or rejump", "Zero score", "Continue anyway"], "correct": 1, "correct_section": "5.4.4"},
            {"id": 7, "question": "The validation window length is how many feet?", "options": ["2,500 feet", "3,000 feet", "3,300 feet", "4,000 feet"], "correct": 2, "correct_section": "2.8.1"},
            {"id": 8, "question": "Competitors shall not carry additional or removable weight. Weight checks may fluctuate by how much?", "options": ["+/- 1kg", "+/- 2kg", "+/- 3kg", "+/- 5kg"], "correct": 1, "correct_section": "3.2.4"},
            {"id": 9, "question": "Each competitor must wear what on every jump?", "options": ["Two PLDs", "Audio altitude warning device", "Video camera", "Tracking device"], "correct": 1, "correct_section": "3.2.8"},
            {"id": 10, "question": "Maximum competitors per exit pass in Speed Skydiving?", "options": ["Four", "Five", "Six", "Eight"], "correct": 2, "correct_section": "5.3.2"},
            {"id": 11, "question": "Speed results are calculated to what precision?", "options": ["1 km/h", "0.1 km/h", "0.01 km/h", "0.001 km/h"], "correct": 2, "correct_section": "5.5.1"},
            {"id": 12, "question": "Exit order in a jump run is determined by what?", "options": ["Random draw", "Registration order", "Personal best descending", "Reverse standings"], "correct": 2, "correct_section": "5.3.1"},
            {"id": 13, "question": "The first person to exit on a pass turns how many degrees to the right?", "options": ["45 degrees", "90 degrees", "180 degrees", "Straight ahead"], "correct": 1, "correct_section": "5.2.3"},
            {"id": 14, "question": "Equipment inspections may be made at any time during competition.", "options": ["True", "False", "Only before competition", "Only after complaint"], "correct": 0, "correct_section": "3.2.3"},
            {"id": 15, "question": "PLD tampering results in what penalty?", "options": ["Warning", "Zero score for jump", "Disqualification", "One-year ban"], "correct": 1, "correct_section": "3.2.13"},
            {"id": 16, "question": "The mixed team score in each round is calculated how?", "options": ["Average of scores", "Sum of scores", "Best score used", "Weighted average"], "correct": 1, "correct_section": "4.2.2"},
            {"id": 17, "question": "Mixed Team Event uses scores from how many rounds?", "options": ["All rounds", "Best 3 rounds", "Last 3 completed rounds", "First 3 rounds"], "correct": 2, "correct_section": "4.2.2"},
            {"id": 18, "question": "If tie cannot be broken after tie-break jump and best round comparison, what happens?", "options": ["Another jump", "Co-medalists declared", "Chief Judge decides", "Draw lots"], "correct": 1, "correct_section": "7.1.2.3"},
            {"id": 19, "question": "Competitors shall not use what systems?", "options": ["GPS systems", "Propulsion systems", "Audio systems", "Video systems"], "correct": 1, "correct_section": "3.2.1"},
            {"id": 20, "question": "The PLD must have a speed accuracy of less than what?", "options": ["1 m/s", "2 m/s", "3 m/s", "5 m/s"], "correct": 2, "correct_section": "3.1.1"},
            {"id": 21, "question": "Additional or removable weight is permitted in Speed Skydiving.", "options": ["True up to 10kg", "True up to 5kg", "False", "Only for training"], "correct": 2, "correct_section": "3.2.4"},
            {"id": 22, "question": "For later rounds, reverse order of ranking may be used at whose discretion?", "options": ["Chief Judge", "Meet Director", "USPA Controller", "Competitors vote"], "correct": 1, "correct_section": "5.1.2"},
            {"id": 23, "question": "The validation window length in meters is approximately what?", "options": ["800 m", "900 m", "1,006 m", "1,200 m"], "correct": 2, "correct_section": "2.8.1"},
            {"id": 24, "question": "The performance window starts when vertical speed first reaches what?", "options": ["5 m/s", "10 m/s", "15 m/s", "20 m/s"], "correct": 1, "correct_section": "2.7.1"},
            {"id": 25, "question": "The performance window ends at 7,400 ft below start OR at what altitude, whichever first?", "options": ["5,000 ft AGL", "5,600 ft AGL (breakoff)", "6,000 ft AGL", "4,500 ft AGL"], "correct": 1, "correct_section": "2.7.1"},
        ]
    },
}
